### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by alekksander** [OpenLauncherTeam/openlauncher#103]
Build version: 0.4.0 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-14 12:26:05 
Device: BullittGroupLimited S40 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
	at com.benny.openlauncher.viewutil.ItemViewFactory.getGroupIconDrawable(ItemViewFactory.java:284)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:234)
	at com.benny.openlauncher.widget.Dock.addItemToPage(Dock.java:211)
	at com.benny.openlauncher.widget.Dock.initDockItem(Dock.java:60)
	at com.benny.openlauncher.activity.Home$4.onAppUpdated(Home.java:284)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:222)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5255)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by dkanada** [comment]
Closing this issue but keeping #96 open since they are duplicates, thanks for the bug report.
