### ISSUE TITLE
Crash when dealing with folders

### ISSUE THREAD

**Issue by mase76** [OpenLauncherTeam/openlauncher#108]
Hi!
I get a crash when dealing with folders on the desktop. Moving icons into or out of folders ends in a crash after some tries. I have to delete the data of OL to be able to use it again.

Build version: 0.4.0 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-15 19:59:57 
Device: Fairphone FP2 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
	at com.benny.openlauncher.viewutil.ItemViewFactory.getGroupIconDrawable(ItemViewFactory.java:284)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:234)
	at com.benny.openlauncher.widget.Desktop.addItemToPage(Desktop.java:281)
	at com.benny.openlauncher.widget.Desktop.initDesktopNormal(Desktop.java:131)
	at com.benny.openlauncher.activity.Home$4.onAppUpdated(Home.java:280)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:222)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by dkanada** [comment]
I think I fixed this a day ago, should be in the next update once we release one. Let me know if you are still having issues after you get the new version though.

**Comment by mase76** [comment]
I still have crashes with folders:

Build version: 0.5.0 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-22 17:59:03 
Device: Fairphone FP2 
 
Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'android.content.Intent com.benny.openlauncher.model.Item.appIntent' on a null object reference
	at com.benny.openlauncher.viewutil.ItemViewFactory.getGroupIconDrawable(ItemViewFactory.java:285)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:110)
	at com.benny.openlauncher.widget.Desktop.addItemToPage(Desktop.java:280)
	at com.benny.openlauncher.widget.Desktop.initDesktopNormal(Desktop.java:136)
	at com.benny.openlauncher.activity.Home$3.onAppUpdated(Home.java:246)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:222)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by dkanada** [comment]
I went back and looked through the code again and I think I actually fixed it this time, thanks for letting me know. I want to add label editing for items but as soon as I finish that I will release a new version to fix the bug.
