### ISSUE TITLE
[Crash] ConcurrentModificationException

### ISSUE THREAD

**Issue by ildar** [OpenLauncherTeam/openlauncher#116]
Adding any application to desktop

Build version: 0.5.0 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-18 18:49:07 
Device: Xiaomi Redmi Note 4 
 
Stack trace:  
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
	at java.util.HashMap$KeyIterator.next(HashMap.java:814)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1446)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1448)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1448)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1448)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1448)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1448)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5800)
	at android.view.ViewRootImpl.-wrap6(ViewRootImpl.java)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3904)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by aabaker** [comment]
A post at https://stackoverflow.com/questions/10988671/java-util-concurrentmodificationexception-in-view-setvisibility claims that calling setVisibility (as onDragEvent() does which is called by DragOptionView::dispatchDragEvent() modifies the list of views that is being iterated over by the Android framework. Trial fix coming up.
