### ISSUE TITLE
Another crash report (clean install and restoring backup) 

### ISSUE THREAD

**Issue by alekksander** [OpenLauncherTeam/openlauncher#126]
Build version: 0.5.0 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-20 09:08:53 
Device: BullittGroupLimited S40 
 
Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'android.content.Intent com.benny.openlauncher.model.Item.appIntent' on a null object reference
	at com.benny.openlauncher.viewutil.ItemViewFactory.getGroupIconDrawable(ItemViewFactory.java:285)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:110)
	at com.benny.openlauncher.widget.Dock.addItemToPage(Dock.java:210)
	at com.benny.openlauncher.widget.Dock.initDockItem(Dock.java:60)
	at com.benny.openlauncher.activity.Home$3.onAppUpdated(Home.java:250)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:222)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5255)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by aabaker** [comment]
Does clean install and restoring backup mean you did a clean install, restored the backup and then had the problem or that you can generate the problem from either a clean install or after restoring a backup. 

I can see code in DatabaseHelper::getSelectionItem() that could end up calling item.items.add() with null as the item to add if the database refers to an item that no longer exists.

From a robustness point of view it is probably a good idea to make ItemViewFactory::getGroupIconDrawable check that the result of item.items.get(i) is not null before using it.

**Comment by alekksander** [comment]
„did a clean install, restored the backup and then had the problem”
