### ISSUE TITLE
crash upon phone restart

### ISSUE THREAD

**Issue by klauf** [OpenLauncherTeam/openlauncher#133]
Hi all

Phone restart after a few days and a bit of customizing the new version of our launcher, I get this error. Any idea? Will try uninstall/reinstall. Thx 

Build version: 0.5.0 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-22 16:13:47 
Device: LeMobile LEX829 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.benny.openlauncher/com.benny.openlauncher.activity.Home}: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.benny.openlauncher.util.DatabaseHelper.getDesktop(DatabaseHelper.java:123)
	at com.benny.openlauncher.widget.Desktop.init(Desktop.java:80)
	at com.benny.openlauncher.activity.Home.initViews(Home.java:289)
	at com.benny.openlauncher.activity.Home.init(Home.java:219)
	at com.benny.openlauncher.activity.Home.onCreate(Home.java:209)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
	... 9 more

**Comment by dkanada** [comment]
How many pages do you have on your desktop?

**Comment by klauf** [comment]
2. 1 widget on each. I reinstalled, working again but the widgets are now empty and I can't move nor remove them

**Comment by dkanada** [comment]
It sounds like you restored from a backup, that copies over the desktop database and if you were having issues with the desktop crashing it was probably an issue in there. For now you can fix the widgets by reinstalling and not restoring from a backup, I will look into the crash.

**Comment by klauf** [comment]
Actually the backup restored itself alone. Your remark intrigued my curiosity so I clear the database, then backuped the empty desktop, uninstalled, wiped every file and directory containing openlauncher, then reinstalled and BIM! I still get a few icons and the 2 pages I had with the first install of openlauncher (ver 0.4.0) with 14 rows... any idea where this setup comes from?

**Comment by gsantner** [comment]
Please install latest available version, clear the app's data in settings and restart OL. Reopen if it still happens.
