### ISSUE TITLE
crash when adding gesture

### ISSUE THREAD

**Issue by kilroythe5th** [OpenLauncherTeam/openlauncher#147]
error details: 

Build version: 0.5.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-25 13:00:31 
Device: LGE Nexus 5 
 
Stack trace:  
android.database.sqlite.SQLiteException: no such table: gesture (code 1): , while compiling: SELECT * FROM gesture WHERE time = 1
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1257)
	at com.benny.openlauncher.util.DatabaseHelper.getGesture(DatabaseHelper.java:290)
	at com.benny.openlauncher.activity.SettingsActivity$SettingsFragmentGestures.onPreferenceTreeClick(SettingsActivity.java:297)
	at android.preference.Preference.performClick(Preference.java:1008)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1211)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3305)
	at android.widget.AbsListView$4.run(AbsListView.java:4228)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by dkanada** [comment]
This is an issue from updating, when we reach 1.0 we will make sure to have backwards compatibility but until then the plan is to remove old legacy code which sometimes breaks current data. I am planning on adding a dialog that will explain this in the app before the next update.

**Comment by dkanada** [comment]
You can fix this by resetting the app data or reinstalling the app.
