### ISSUE TITLE
crash when moving items

### ISSUE THREAD

**Issue by alugarius** [OpenLauncherTeam/openlauncher#154]
Build version: 0.5.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-30 22:05:09 
Device: Samsung GT-I9300 
 
Stack trace:  
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
	at java.util.HashMap$KeyIterator.next(HashMap.java:833)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1216)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1218)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1218)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1218)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1218)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1218)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5722)
	at android.view.ViewRootImpl.access$1200(ViewRootImpl.java:139)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3775)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by dkanada** [comment]
@aabaker is this the same crash that you were working on before?

**Comment by aabaker** [comment]
I was looking at #116 and made the change in https://github.com/OpenLauncherTeam/openlauncher/commit/ad7f60814f41309540c04f4da8bfccd5ae4186eb This crash log looks very similar and that commit was merged just after the 0.5.1 release so this could well be fixed by the same patch

**Comment by michaelof** [comment]
(Android 4.4.2)

Seems that I get the same error details for my crash(es):

`Build version: 0.5.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-01 18:27:06 
Device: Malata Cynus T8 
 
Stack trace:  
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
	at java.util.HashMap$KeyIterator.next(HashMap.java:833)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1222)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1224)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1224)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1224)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1224)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1224)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5465)
	at android.view.ViewRootImpl.access$1200(ViewRootImpl.java:106)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3610)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5333)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
`

I'm getting this reproducible every time I'm trying to place an app from the "app pool" (where all installed apps are shown) to the "desktop" / openLauncher start screen.

Good news is that although openLauncher crashes, the operation itself was succesful, the app was places where  want(ed) it


Regards,
Michael

**Comment by ildar** [comment]
Yep, exactly the same exception. Definitely the dup.

**Comment by alugarius** [comment]
Is it fixed now?
