### ISSUE TITLE
Crashing when adding apps to desktop

### ISSUE THREAD

**Issue by luisavilesmx** [OpenLauncherTeam/openlauncher#156]
Here the problem as the report was given

Build version: 0.5.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-02 04:16:01 
Device: Hisense C1 
 
Stack trace:  
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
	at java.util.HashMap$KeyIterator.next(HashMap.java:814)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1277)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1279)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1279)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1279)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1279)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1279)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5199)
	at android.view.ViewRootImpl.access$600(ViewRootImpl.java:99)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3387)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5270)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)

**Comment by ildar** [comment]
dup of https://github.com/OpenLauncherTeam/openlauncher/issues/116
plz search before you post.

**Comment by dkanada** [comment]
Should be fixed for the next update, we will keep the original issue open until then.
