### ISSUE TITLE
Crash when I open some app

### ISSUE THREAD

**Issue by sguinetti** [OpenLauncherTeam/openlauncher#160]
Hello, I use the F-droid app and Android 7. I add a telephone app, when I open this access, the launcher crashes. This is a log:

Build version: 0.5.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-08 07:17:38 
Device: Sony E6883 
 
Stack trace:  
android.content.ActivityNotFoundException: No Activity found to handle Intent {  }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1816)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
	at android.app.Activity.startActivityForResult(Activity.java:4265)
	at android.app.Activity.startActivityForResult(Activity.java:4224)
	at android.app.Activity.startActivity(Activity.java:4548)
	at android.app.Activity.startActivity(Activity.java:4516)
	at com.benny.openlauncher.widget.AppItemView$Builder$3$1.run(AppItemView.java:224)
	at com.benny.openlauncher.util.Tool$7$1.run(Tool.java:555)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6217)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by gsantner** [comment]
See #157
