### ISSUE TITLE
Crash when adding Dialer/Phone app to tray

### ISSUE THREAD

**Issue by AliceGrey** [OpenLauncherTeam/openlauncher#161]
OpenLauncher crashes when adding the phone app to the bottom tray. Running Lineage OS 7.1.2. 

Crash code:
Build version: 0.5.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-09 21:12:45 
Device: LGE LG-VS985 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
	at com.benny.openlauncher.util.AppManager.findApp(AppManager.java:64)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.<init>(GroupIconDrawable.java:48)
	at com.benny.openlauncher.widget.AppItemView$Builder.setGroupItem(AppItemView.java:234)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:92)
	at com.benny.openlauncher.widget.Dock.addItemToPage(Dock.java:210)
	at com.benny.openlauncher.widget.Desktop.handleOnDropOver(Desktop.java:555)
	at com.benny.openlauncher.widget.Dock.onDrag(Dock.java:134)
	at android.view.View.callDragEventHandler(View.java:20902)
	at android.view.View.dispatchDragEvent(View.java:20893)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1510)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5557)
	at android.view.ViewRootImpl.-wrap7(ViewRootImpl.java)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3671)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by dkanada** [comment]
Are you adding it into a group and are you using a release from F-Droid?

**Comment by klauf** [comment]
Hey dkanada, I guess I have the same issue, though not only with phone app. See #162. 
I just try to add the icon on an empty space in the dock. And I'm using the latest F-Droid release. 
Cheers

**Comment by AliceGrey** [comment]
Latest F-droid release, adding it to empty space on the dock.

**Comment by 12people** [comment]
Same issue, latest F-Droid release, trying to drag Chrome into the dock.

Details:
Build version: 0.5.3 
Build date: 1980-01-01 00:00:00 
Current date: 2017-07-09 22:32:59 
Device: LGE Nexus 5

**Comment by meradoou** [comment]
Same issue with F-Droid Version. Wipe app data to restore it
