### ISSUE TITLE
Crash when trying to launch poweramp

### ISSUE THREAD

**Issue by 0uro** [OpenLauncherTeam/openlauncher#163]
Build version: 0.5.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-12 17:05:17 
Device: OnePlus ONE E1003 
 
Stack trace:  
android.content.ActivityNotFoundException: No Activity found to handle Intent {  }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1818)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
	at android.app.Activity.startActivityForResult(Activity.java:4229)
	at android.app.Activity.startActivityForResult(Activity.java:4187)
	at android.app.Activity.startActivity(Activity.java:4526)
	at android.app.Activity.startActivity(Activity.java:4494)
	at com.benny.openlauncher.widget.AppItemView$Builder$3$1.run(AppItemView.java:224)
	at com.benny.openlauncher.util.Tool$7$1.run(Tool.java:555)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by gsantner** [comment]
... please check issues before creating a new one
