### ISSUE TITLE
Total crash

### ISSUE THREAD

**Issue by urbanomad64** [OpenLauncherTeam/openlauncher#164]
I started up this morning and folders with more than one app in them opened with only  one app and looked a bit strange. I moved the one app outside to see if that would change anything. I got this crash and it kept crashing when I clicked on Close App button. After 3 or 4 a times, I had to choose a launcher and I selected my system default. Everything was working well since 0.5.1 was released and all of a sudden this morning, it didn't work

Build0.5.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-17 05:07:33 
Device: UMI SUPER 
 
Stack trace:  
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:533)
	at java.lang.Integer.parseInt(Integer.java:556)
	at com.benny.openlauncher.util.DatabaseHelper.getSelectionItem(DatabaseHelper.java:272)
	at com.benny.openlauncher.util.DatabaseHelper.getDesktop(DatabaseHelper.java:123)
	at com.benny.openlauncher.widget.Desktop$DesktopAdapter.getItemFromCoordinate(Desktop.java:442)
	at com.benny.openlauncher.widget.Desktop$DesktopAdapter.access$100(Desktop.java:342)
	at com.benny.openlauncher.widget.Desktop$DesktopAdapter$2.onItemRearrange(Desktop.java:464)
	at com.benny.openlauncher.widget.CellContainer.onItemRearrange(CellContainer.java:139)
	at com.benny.openlauncher.widget.CellContainer.peekItemAndSwap(CellContainer.java:130)
	at com.benny.openlauncher.widget.Desktop.onDrag(Desktop.java:204)
	at android.view.View.dispatchDragEvent(View.java:21128)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1526)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1521)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1521)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1521)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1521)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1521)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1521)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6051)
	at android.view.ViewRootImpl.-wrap7(ViewRootImpl.java)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4096)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by tidux** [comment]
Confirmed, exact same behavior including a crash loop.

**Comment by BennyKok** [comment]
is this still happening? :(
