### ISSUE TITLE
Constant crashing after upgrading to 0.5.2

### ISSUE THREAD

**Issue by urbanomad64** [OpenLauncherTeam/openlauncher#175]
Build version: 0.5.2 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-29 08:35:45 
Device: UMI SUPER 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1368)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.draw(GroupIconDrawable.java:110)
	at com.benny.openlauncher.widget.AppItemView.onDraw(AppItemView.java:149)
	at android.view.View.draw(View.java:17320)
	at android.view.View.buildDrawingCacheImpl(View.java:16578)
	at android.view.View.buildDrawingCache(View.java:16432)
	at android.view.View.draw(View.java:17062)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.draw(View.java:17332)
	at android.view.View.updateDisplayListIfDirty(View.java:16259)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.draw(View.java:17332)
	at com.benny.openlauncher.widget.SmoothViewPager.draw(SmoothViewPager.java:2306)
	at android.view.View.updateDisplayListIfDirty(View.java:16259)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:844)
	at android.view.View.draw(View.java:17332)
	at com.android.internal.policy.DecorView.draw(DecorView.java:830)
	at android.view.View.updateDisplayListIfDirty(View.java:16259)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3188)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2981)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2569)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
	at android.view.Choreographer.doCallbacks(Choreographer.java:709)
	at android.view.Choreographer.doFrame(Choreographer.java:644)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by urbanomad64** [comment]
I finally was able to get to the system settings and deleted caches and started to rebuild my home screen. I dragged an app from the app drawer on top of another and the whole thing started a crash loop again
Build version: 0.5.2 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-29 08:55:17 
Device: UMI SUPER 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1368)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.draw(GroupIconDrawable.java:110)
	at com.benny.openlauncher.widget.AppItemView.onDraw(AppItemView.java:149)
	at android.view.View.draw(View.java:17320)
	at android.view.View.buildDrawingCacheImpl(View.java:16578)
	at android.view.View.buildDrawingCache(View.java:16432)
	at android.view.View.draw(View.java:17062)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.draw(View.java:17332)
	at android.view.View.updateDisplayListIfDirty(View.java:16259)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3188)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2981)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2569)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
	at android.view.Choreographer.doCallbacks(Choreographer.java:709)
	at android.view.Choreographer.doFrame(Choreographer.java:644)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by ildar** [comment]
I wonder if devs can spend 5 minutes for playing/testing the launcher back
and forth BEFORE releasing? cause every release appears crashy and
disappointing

**Comment by antsuke42** [comment]
confirmed.
new install, tried to make a folder.


Build version: 0.5.2 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-29 13:15:29 
Device: Motorola MotoG3 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1368)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.draw(GroupIconDrawable.java:110)
	at com.benny.openlauncher.widget.AppItemView.onDraw(AppItemView.java:149)
	at android.view.View.draw(View.java:17189)
	at android.view.View.buildDrawingCacheImpl(View.java:16478)
	at android.view.View.buildDrawingCache(View.java:16339)
	at android.view.View.getDrawingCache(View.java:16245)
	at android.view.View.draw(View.java:16949)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.draw(View.java:17192)
	at android.view.View.updateDisplayListIfDirty(View.java:16171)
	at android.view.View.draw(View.java:16955)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.draw(View.java:17192)
	at com.benny.openlauncher.widget.SmoothViewPager.draw(SmoothViewPager.java:2306)
	at android.view.View.updateDisplayListIfDirty(View.java:16171)
	at android.view.View.draw(View.java:16955)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16166)
	at android.view.View.draw(View.java:16955)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16166)
	at android.view.View.draw(View.java:16955)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16166)
	at android.view.View.draw(View.java:16955)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16166)
	at android.view.View.draw(View.java:16955)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.updateDisplayListIfDirty(View.java:16166)
	at android.view.View.draw(View.java:16955)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
	at android.view.View.draw(View.java:17192)
	at com.android.internal.policy.DecorView.draw(DecorView.java:756)
	at android.view.View.updateDisplayListIfDirty(View.java:16171)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by gsantner** [comment]
@ildar OpenLauncher is still alpha software and still under heavy work. We are currently working on something that may improve a lot and pretty sure will also fix this bug.

**Comment by BennyKok** [comment]
I am so sorry for not being spending those 5 mins, but next times, we'll test before tag the release.

**Comment by ildar** [comment]
@BennyKok , thanks for understanding. Hope no offense had gotten.

**Comment by BennyKok** [comment]
@ildar it is ok, I understand, this is our duty.

**Comment by spaetz** [comment]
Yep, happens when you try to create a folder with multiple icons in the dock.

**Comment by dkanada** [comment]
I just fixed it, we will test it out tomorrow. If anyone here wants to clone the repo to try it out they can.

**Comment by icaruseffect** [comment]
I just compiled from master with your fix included. I have had no issues so far creating folders.

**Comment by urbanomad64** [comment]
Is this fix being pushed to f-droid?

**Comment by dkanada** [comment]
Already released the fix but F-Droid only scans for new releases every few days or something so we are just waiting it out now.

**Comment by urbanomad64** [comment]
Thank you!

**Comment by urbanomad64** [comment]
Just got 0.5.3 from f-droid and cleared data and all seems well in this version
