### ISSUE TITLE
Crash when moving one icon over another

### ISSUE THREAD

**Issue by alexander-n8hgeg5e** [OpenLauncherTeam/openlauncher#176]
#### General information

* **Device:**   Sony Xperia Z1 Compact
* **Android Version:**  5.1.1 (cyanogenmod 12.1)
* **App version:**  0.5.2

#### Steps to reproduce
0. deinstall app (maybe not needed)
1. install app
2. move icon from app drawer to home screen
3. move another icon to home screen
4. move one icon quickly and centered over the another.

#### Expected result
I tried to create a directory.
I still don't know how to.

#### What do i see instead?

OpenLauncher  "Rip-Screen",
with message unexpected error.
After that the app shows the rip-screen
in situations that were ok .

#### stack trace from the rip screen:

Build version: 0.5.2 
Build date: 1980-01-01 00:00:00 
Current date: 2017-06-29 14:41:30 
Device: Sony Xperia Z1 Compact 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1281)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1369)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.draw(GroupIconDrawable.java:110)
	at com.benny.openlauncher.widget.AppItemView.onDraw(AppItemView.java:149)
	at android.view.View.draw(View.java:15247)
	at android.view.View.buildDrawingCacheImpl(View.java:14493)
	at android.view.View.buildDrawingCache(View.java:14355)
	at android.view.View.updateDisplayListIfDirty(View.java:14164)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.draw(View.java:15250)
	at android.view.View.updateDisplayListIfDirty(View.java:14183)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.draw(View.java:15250)
	at com.benny.openlauncher.widget.SmoothViewPager.draw(SmoothViewPager.java:2306)
	at android.view.View.updateDisplayListIfDirty(View.java:14183)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.draw(View.java:15250)
	at android.widget.FrameLayout.draw(FrameLayout.java:598)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2906)
	at android.view.View.updateDisplayListIfDirty(View.java:14183)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2536)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by gsantner** [comment]
..
