### ISSUE TITLE
Crash and settings corruption when dragging icon onto icon

### ISSUE THREAD

**Issue by Bugsbane** [OpenLauncherTeam/openlauncher#177]
#### General information

* **Device:**   Samsung Galaxy s5
* **Android Version:**  Android 6.0.1
* **App version:**  0.5.2 (via fdroid)

#### Steps to reproduce

1. Drag app icon on homescreen on top of another homescreen app icon
2. …
3. …

#### Expected result
Icons either: 1. swap locations, 2. move other icons to make a space or 3. create a "folder" of icons that expand when tapped, as in the default Google launcher.

**What do you see instead?**
Crash whenever Open Launcher runs, even after restarting my phone and changing to another launcher and back. Gives the "rip" screen and the following log:

Build version: 0.5.2 
Build date: 1980-01-01 00:00:00 
Current date: 2017-07-02 05:45:26 
Device: Samsung SM-G900W8 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1300)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1388)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.draw(GroupIconDrawable.java:110)
	at com.benny.openlauncher.widget.AppItemView.onDraw(AppItemView.java:149)
	at android.view.View.draw(View.java:17469)
	at android.view.View.buildDrawingCacheImpl(View.java:16764)
	at android.view.View.buildDrawingCache(View.java:16625)
	at android.view.View.draw(View.java:17231)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	at android.view.View.draw(View.java:17472)
	at android.view.View.updateDisplayListIfDirty(View.java:16464)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	at android.view.View.draw(View.java:17472)
	at com.benny.openlauncher.widget.SmoothViewPager.draw(SmoothViewPager.java:2306)
	at android.view.View.updateDisplayListIfDirty(View.java:16464)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
	at android.view.View.draw(View.java:17472)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3205)
	at android.view.View.updateDisplayListIfDirty(View.java:16464)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3135)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2934)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2523)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1438)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7398)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by gsantner** [comment]
there are 4 issiues now about this...use aearch
