### ISSUE TITLE
Folder bug

### ISSUE THREAD

**Issue by MFlisar** [OpenLauncherTeam/openlauncher#192]
**Recreation steps:**

* create a folder on the desktop with 2 items
* drag out item 1 to resolve the folder
* drag one item over the other again to recreate the folder
* drag out item 2 of the folder
* repeat this folder resolving and recreation a few times and the app will crash

**Exception:**

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.benny.openlauncher.core.model.Item.setX(int)' on a null object reference
at com.benny.openlauncher.core.widget.GroupPopupView.updateItem(GroupPopupView.java:219)
at com.benny.openlauncher.core.widget.GroupPopupView$2.onLongClick(GroupPopupView.java:123)
at android.view.View.performLongClickInternal(View.java:6276)
at android.view.View.performLongClick(View.java:6234)
at android.view.View.performLongClick(View.java:6252)
at android.view.View$CheckForLongPress.run(View.java:23616)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Observations:**

* after the crash an empty folder is shown on desktop (only if you use my last version, otherwise the app will crash infinitely)
* this folder can't be removed normally
* drag any item on this folder, app will crash again and afterwards the item and folder are gone

**Other observations:**

* while creating folders it happens that a folder is create at a wrong position. For example item 1 is positioned at (1,1) and I drag item 2 over it and this creates a folder at (1,2)
* sometimes I see an empty folder overlapped by an icon but I can't recreate this and sometimes I see overlapped items which I can't recreate either; long pressing such items makes them vanish completely (not sure if this is always true but most of the time it is)

**Comment by Abounding** [comment]
I can't seem to recreate this bug. Could it be device specific?

**Comment by dkanada** [comment]
I don't think the bug is device specific, folders probably have a few edge cases we have yet to discover.

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
