### ISSUE TITLE
NullPointerException creating folder - now app will not start

### ISSUE THREAD

**Issue by joeytwiddle** [OpenLauncherTeam/openlauncher#200]
I installed the app a few days ago. I added Facebook to the home screen, and then Twitter. Then I dropped Twitter on top of Facebook, trying to create a group/folder, but it crashed with this error:

<details>
Build version: 0.5.1 
Build date: 1979-11-30 00:00:00 
Current date: 2017-07-27 22:50:18 
Device: OPPO A11w 
 
Stack trace:  
java.lang.NullPointerException
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1083)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1170)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.draw(GroupIconDrawable.java:110)
	at com.benny.openlauncher.widget.AppItemView.onDraw(AppItemView.java:149)
	at android.view.View.draw(View.java:14742)
	at android.view.View.buildDrawingCache(View.java:13929)
	at android.view.View.getDisplayList(View.java:13558)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14753)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14753)
	at com.benny.openlauncher.widget.SmoothViewPager.draw(SmoothViewPager.java:2306)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14753)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2427)
	at android.view.View.draw(View.java:14753)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2407)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1627)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1506)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2740)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2605)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2228)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1194)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6268)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5344)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
</details>

<br>

Ever since then, whenever I try to start the launcher, I get the following error.

<details>
Build version: 0.5.1 
Build date: 1979-11-30 00:00:00 
Current date: 2017-07-27 22:42:43 
Device: OPPO A11w 
 
Stack trace:  
java.lang.NullPointerException
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1083)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1170)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.draw(GroupIconDrawable.java:110)
	at com.benny.openlauncher.widget.AppItemView.onDraw(AppItemView.java:149)
	at android.view.View.draw(View.java:14742)
	at android.view.View.buildDrawingCache(View.java:13929)
	at android.view.View.getDisplayList(View.java:13558)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14753)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14753)
	at com.benny.openlauncher.widget.SmoothViewPager.draw(SmoothViewPager.java:2306)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14753)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2427)
	at android.view.View.draw(View.java:14753)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2407)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1627)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1506)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2740)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2605)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2228)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1194)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6268)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5344)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
</details>

**Comment by joeytwiddle** [comment]
Build version: 0.5.1 
Build date: 1979-11-30 00:00:00 
Current date: 2017-07-27 22:50:18 
Device: OPPO A11w 
 
Stack trace:  
java.lang.NullPointerException
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1083)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1170)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.draw(GroupIconDrawable.java:110)
	at com.benny.openlauncher.widget.AppItemView.onDraw(AppItemView.java:149)
	at android.view.View.draw(View.java:14742)
	at android.view.View.buildDrawingCache(View.java:13929)
	at android.view.View.getDisplayList(View.java:13558)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14753)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14753)
	at com.benny.openlauncher.widget.SmoothViewPager.draw(SmoothViewPager.java:2306)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14753)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14444)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2427)
	at android.view.View.draw(View.java:14753)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2407)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1627)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1506)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2740)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2605)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2228)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1194)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6268)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5344)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by MFlisar** [comment]
I'm quite sure this is exception is old and won't happen with the current master branch, am I right? Or are you using the current master branch?

**Comment by joeytwiddle** [comment]
I am not using the master branch. I am using the version in the app store.

**Comment by MFlisar** [comment]
If you don't mind, clear your app data, otherwise you'll have to wait for an update because you can't compile a valid app that can upgrade your play store version yourself.

Alternatively use the master branch and replace the app store's app...

**Comment by joeytwiddle** [comment]
I cleared data and installed F-Droid and then the F-Droid version. This version works much better, thanks!

I hope a more stable release can make it onto the Play Store soon.
