### ISSUE TITLE
[Bug] Homescreen empty, only force-close via settings works

### ISSUE THREAD

**Issue by conrad-heimbold** [OpenLauncherTeam/openlauncher#206]
-----------------------------

#### General information

* **App version:** 0.5.3 from F-Droid
* **Android Version:** LineageOS 14.1

#### Expected result
**What is expected?** Homescreen shows up (including all the widgets; the app list button, and all dragged app icons) 

**What does happen instead?** 
Only the time + search button in the top row shows up. If I click on search at the top, and search for any app; no app shows up (just blank). Everything else is blank. 
The side bar has been disabled, so I can't open it neither. 
I don't get any message that "openlauncher has been stopped.", the screen is just empty. 

The only way to get openlauncher work again; is to force-close it via settings. 

#### Steps to reproduce
* I don't know how to reproduce it. 

### ADB Logcat
I don't know if this logcat includes the relevant information for this specific crash. 
```
--------- beginning of system
07-31 22:26:30.118  1105  1105 E ActivityThread: Activity com.benny.openlauncher.activity.Home has leaked IntentReceiver com.benny.openlauncher.activity.Home$1@7d7db7c that was originally registered here. Are you missing a call to unregisterReceiver()?
07-31 22:26:30.118  1105  1105 E ActivityThread: android.app.IntentReceiverLeaked: Activity com.benny.openlauncher.activity.Home has leaked IntentReceiver com.benny.openlauncher.activity.Home$1@7d7db7c that was originally registered here. Are you missing a call to unregisterReceiver()?
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1276)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at com.benny.openlauncher.activity.Home.registerBroadcastReceiver(Home.java:620)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at com.benny.openlauncher.activity.Home.init(Home.java:218)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at com.benny.openlauncher.activity.Home.onCreate(Home.java:206)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.Activity.performCreate(Activity.java:6684)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.os.Looper.loop(Looper.java:154)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-31 22:26:30.118  1105  1105 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
--------- beginning of main
07-31 22:26:33.463  1105  1123 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
07-31 22:26:33.464  1105  1123 I OpenGLRenderer: Initialized EGL, version 1.4
07-31 22:26:33.464  1105  1123 D OpenGLRenderer: Swap behavior 1
07-31 22:26:33.466  1105  1123 W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
07-31 22:27:08.720  1105  1123 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
07-31 22:27:08.720  1105  1123 I OpenGLRenderer: Initialized EGL, version 1.4
07-31 22:27:08.720  1105  1123 D OpenGLRenderer: Swap behavior 1
07-31 22:27:08.723  1105  1123 W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
07-31 22:27:14.304  1105  1123 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
07-31 22:27:14.304  1105  1123 I OpenGLRenderer: Initialized EGL, version 1.4
07-31 22:27:14.305  1105  1123 D OpenGLRenderer: Swap behavior 1
07-31 22:27:14.306  1105  1123 W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
07-31 22:27:22.033  1105  1105 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
07-31 22:27:37.254  1105  1123 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
07-31 22:27:37.255  1105  1123 I OpenGLRenderer: Initialized EGL, version 1.4
07-31 22:27:37.255  1105  1123 D OpenGLRenderer: Swap behavior 1
07-31 22:27:37.259  1105  1123 W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
07-31 22:27:40.901  1105  1123 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
07-31 22:27:40.901  1105  1123 I OpenGLRenderer: Initialized EGL, version 1.4
07-31 22:27:40.901  1105  1123 D OpenGLRenderer: Swap behavior 1
07-31 22:27:40.903  1105  1123 W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
07-31 22:28:01.372  1105  1105 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
```

**Comment by BennyKok** [comment]
this happen frequently?

**Comment by conrad-heimbold** [comment]
@BennyKok 
no, not frequently; maybe once or twice

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
