### ISSUE TITLE
[Crash] NullPointerException: Attempt to invoke virtual method 'long ...VirtualRefBasePtr.get

### ISSUE THREAD

**Issue by ildar** [OpenLauncherTeam/openlauncher#207]
Build version: 0.5.3 
Build date: 1980-01-01 00:00:00 
Current date: 2017-08-01 19:18:16 
Device: Samsa SM-G710K 

Stack trace: 
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.android.internal.util.VirtualRefBasePtr.get()' on a null object reference
at android.view.RenderNodeAnimator.applyInterpolator(RenderNodeAnimator.java:171)
at android.view.RenderNodeAnimator.start(RenderNodeAnimator.java:185)
at com.benny.openlauncher.widget.AppDrawerController$3.run(AppDrawerController.java:145)
at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1119)
at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:603)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5471)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
