### ISSUE TITLE
How do I clear the settings (to escape from a crash loop)?

### ISSUE THREAD

**Issue by joeytwiddle** [OpenLauncherTeam/openlauncher#213]
I am stuck in a crash loop, the launcher crashes each time I load it.

What I really want to do is to clear the settings to defaults, and then load from my backup settings.

Things I have tried:

- Used a file explorer to navigate to `/OpenLauncher` and removed the two files in there (*Edit: Turns out these were not actively used: they are the backup files*)
- Went into phone's settings to find the app. Cleared the cache, but could not clear the data because the button to do that is disabled. (In fact Force stop and Uninstall are also disabled! However if I leave the app info page and go back to the list of apps, then the Uninstall button there works fine. Oppo Joy 3 here. I installed OpenLauncher from F-Droid.)

**How do you all clear your settings?** (Let's add it to the Wiki!) (Uninstall will be my last resort.)

----

By the way, here is the crash trace:

<details>
Build version: 0.5.3 
Build date: 1980-01-01 00:00:00 
Current date: 2017-08-08 01:14:18 
Device: OPPO A11w 
 
Stack trace:  
java.lang.NullPointerException
	at com.benny.openlauncher.util.AppManager.findApp(AppManager.java:61)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.<init>(GroupIconDrawable.java:46)
	at com.benny.openlauncher.widget.AppItemView$Builder.setGroupItem(AppItemView.java:226)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:85)
	at com.benny.openlauncher.widget.Desktop.addItemToPage(Desktop.java:281)
	at com.benny.openlauncher.widget.Desktop.initDesktopNormal(Desktop.java:102)
	at com.benny.openlauncher.activity.Home$3.onAppUpdated(Home.java:237)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:221)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5344)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
</details>

**Comment by dkanada** [comment]
Currently there isn't a way without entering the OpenLauncher settings or clearing the app data. @BennyKok can we add a button in the crash activity to reset the database? That would fix these kinds of issues. For now I would suggest reinstalling and restoring from the last backup you saved before the crashes started.

**Comment by BennyKok** [comment]
@dkanada I want to do that to, we need to create custom activity and implement the require method for the crash catcher lib that we were using.

**Comment by joeytwiddle** [comment]
Some notes that may be useful for others:

In my OS's Apps menu, under OpenLauncher, there was no option to Clear Data. It turns out the reason for this was that OpenLauncher was an active "Device Manager".

When I hit Uninstall, my OS prompted me to remove OpenLauncher from the "Device Managers" list. After I did this, then I could clear the app data, and I didn't need to uninstall!

**Comment by gsantner** [comment]
@BennyKok What about that idea:
After the second crash in half an hour:
* Let the ol crash handler windows show an second button "Reset app"
* OnClick explain what it will do in a dialog
* If he accepts that, ask again if he really  wanna do that, because it will delete everything

**Comment by BennyKok** [comment]
I think that is ok, but maybe just always showing the reset button will be
also fine?

**Comment by dkanada** [comment]
I agree, just leave the reset button there, no harm in letting people choose if they want to reset.

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
