### ISSUE TITLE
0.5.4 crash report

### ISSUE THREAD

**Issue by alekksander** [OpenLauncherTeam/openlauncher#220]
This is freshly configured setup. Bubble is sometimes highlighted for no apparent reason (screenshot). App crashes on short tap on it. On long tap the highlight disappears and crash doesn't occur.

```
Build version: 0.5.4 

Build date: 1979-11-30 00:00:00 

Current date: 2017-08-16 16:57:39 

Device: BullittGroupLimited S40 

 

Stack trace:  

java.lang.NullPointerException: Attempt to invoke virtual method 'com.benny.openlauncher.core.model.Item$Type com.benny.openlauncher.core.model.Item.getType()' on a null object reference

	at com.benny.openlauncher.core.widget.GroupPopupView.showWindowV(GroupPopupView.java:106)

	at com.benny.openlauncher.core.widget.AppItemView$Builder$4.onClick(AppItemView.java:317)

	at android.view.View.performClick(View.java:4781)

	at android.view.View$PerformClick.run(View.java:19874)

	at android.os.Handler.handleCallback(Handler.java:739)

	at android.os.Handler.dispatchMessage(Handler.java:95)

	at android.os.Looper.loop(Looper.java:135)

	at android.app.ActivityThread.main(ActivityThread.java:5255)

	at java.lang.reflect.Method.invoke(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:372)

	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

![screenshot_2017-08-16-16-57-48](https://user-images.githubusercontent.com/3148302/29372594-e380f2dc-82ab-11e7-9ebf-972209112e10.png)

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
