### ISSUE TITLE
Crashes after deleting an app

### ISSUE THREAD

**Issue by namjmnam** [OpenLauncherTeam/openlauncher#227]
#### General information

* **App version:**
0.5.3
* **Android Version:**
Google Nexus 6.0.1

#### Expected result
**What is expected?**
I deleted an app(Google Play Console) from the store(not from the launcher) and the launcher popped a crashing message. I tried to go back to the launcher and it keeps showing me the same message.

**What does happen instead?**
It crashed. Below is the log I copied from the error message.

Build version: 0.5.3 
Build date: 1980-01-01 00:00:00 
Current date: 2017-09-01 12:55:28 
Device: LGE Nexus 5 
 
Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'android.graphics.drawable.Drawable com.benny.openlauncher.util.AppManager$App.icon' on a null object reference
	at com.benny.openlauncher.viewutil.GroupIconDrawable.<init>(GroupIconDrawable.java:46)
	at com.benny.openlauncher.widget.AppItemView$Builder.setGroupItem(AppItemView.java:226)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:85)
	at com.benny.openlauncher.widget.Desktop.addItemToPage(Desktop.java:281)
	at com.benny.openlauncher.widget.Desktop.initDesktopNormal(Desktop.java:102)
	at com.benny.openlauncher.activity.Home$3.onAppUpdated(Home.java:237)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:221)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

#### Steps to reproduce
*

**Comment by christianfl** [comment]
Same issue. App was on the Homescreen. After installing the app again the issue was gone.

**Comment by conrad-heimbold** [comment]
Same issue here: 
Build version: 0.5.5 
Build date: 1980-01-01 00:00:00 
Current date: 2018-01-01 13:55:18 
Device: Motorola Moto G Play 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.benny.openlauncher.core.widget.Desktop.initDesktopNormal(com.benny.openlauncher.core.activity.Home)' on a null object reference
	at com.benny.openlauncher.core.activity.Home$6.onAppDeleted(Home.java:326)
	at com.benny.openlauncher.util.AppManager.notifyRemoveListeners(AppManager.java:205)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:299)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening on latest version
