### ISSUE TITLE
after changing drawer view to paged, on the last page crash

### ISSUE THREAD

**Issue by samansalamat** [OpenLauncherTeam/openlauncher#235]
09-14 13:17:33.036 24772-24772/com.benny.openlauncher E/InputEventReceiver: Exception dispatching input event.
09-14 13:17:33.036 24772-24772/com.benny.openlauncher E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-14 13:17:33.037 24772-24772/com.benny.openlauncher E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean in.championswimmer.sfg.lib.SimpleFingerGestures.onTouch(android.view.View, android.view.MotionEvent)' on a null object reference
                                                                              at com.benny.openlauncher.core.widget.CellContainer.onTouchEvent(CellContainer.java:202)
                                                                              at android.view.View.dispatchTouchEvent(View.java:9415)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2660)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2304)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                              at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2453)
                                                                              at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1772)
                                                                              at android.app.Activity.dispatchTouchEvent(Activity.java:2808)
                                                                              at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2414)
                                                                              at android.view.View.dispatchPointerEvent(View.java:9646)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4753)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4611)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4116)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4169)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4135)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4281)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4143)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4338)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4116)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4169)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4135)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4143)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4116)
                                                                              at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6570)
                                                                              at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6544)
                                                                              at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6487)
                                                                              at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6742)
                                                                              at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                              at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                              at android.os.MessageQueue.next(MessageQueue.java:328)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5765)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                          	at com.android.internal.os.Zy
09-14 13:17:33.038 24772-24772/com.benny.openlauncher D/AndroidRuntime: Shutting down VM
09-14 13:17:33.038 24772-24772/com.benny.openlauncher E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'boolean in.championswimmer.sfg.lib.SimpleFingerGestures.onTouch(android.view.View, android.view.MotionEvent)' on a null object reference
                                                                                   at com.benny.openlauncher.core.widget.CellContainer.onTouchEvent(CellContainer.java:202)
                                                                                   at android.view.View.dispatchTouchEvent(View.java:9415)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2660)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2304)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2453)
                                                                                   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1772)
                                                                                   at android.app.Activity.dispatchTouchEvent(Activity.java:2808)
                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2414)
                                                                                   at android.view.View.dispatchPointerEvent(View.java:9646)
                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4753)
                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4611)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4116)
                                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4169)
                                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4135)
                                                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4281)
                                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4143)
                                                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4338)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4116)
                                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4169)
                                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4135)
                                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4143)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4116)
                                                                                   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6570)
                                                                                   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6544)
                                                                                   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6487)
                                                                                   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6742)
                                                                                   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                   at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                   at android.os.MessageQueue.next(MessageQueue.java:328)
                                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5765)
09-14 13:17:33.064 24772-24772/com.benny.openlauncher I/Process: Sending signal. PID: 24772 SIG: 9

**Comment by BennyKok** [comment]
ok

**Comment by samansalamat** [comment]
could u fix it?

**Comment by BennyKok** [comment]
Not sure if this has been fixed, as I cant reproduce this problem.
