### ISSUE TITLE
OL crashed after deleting app with active desktopwidget

### ISSUE THREAD

**Issue by Aiurek** [OpenLauncherTeam/openlauncher#240]
Immediately after I deleted Simple Notes, OL crashed, which might be connected to the still active Simple Notes widget on my desktop during the deinstallation. The space where the widget used to be showed an error afterwards.

Android 7.0
Build version: 0.5.4 
Build date: 1979-11-30 00:00:00 
Current date: 2017-09-28 17:08:24 
Device: Motorola Moto G (4) 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.benny.openlauncher.core.widget.Desktop.initDesktopNormal(com.benny.openlauncher.core.activity.Home)' on a null object reference
	at com.benny.openlauncher.core.activity.Home$6.onAppDeleted(Home.java:298)
	at com.benny.openlauncher.util.AppManager.notifyRemoveListeners(AppManager.java:212)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:306)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
