### ISSUE TITLE
Cannot Launch Apps With Gestures.

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [OpenLauncherTeam/openlauncher#256]
After updating from F-Droid (OL version 0.5.5), I can no longer launch apps using gestures.

Error Report:

Build version: 0.5.5 
Build date: 1980-01-01 00:00:00 
Current date: 2017-10-02 
Device: 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
	at com.benny.openlauncher.util.Tool.startApp(Tool.java:196)
	at com.benny.openlauncher.util.LauncherAction.RunAction(LauncherAction.java:44)
	at com.benny.openlauncher.activity.Home$7.onDrawerGesture(Home.java:335)
	at com.benny.openlauncher.core.viewutil.DesktopGestureListener.onSwipeUp(DesktopGestureListener.java:29)
	at in.championswimmer.sfg.lib.SimpleFingerGestures.doCallBack(SimpleFingerGestures.java:110)
	at in.championswimmer.sfg.lib.SimpleFingerGestures.onTouch(SimpleFingerGestures.java:79)
	at com.benny.openlauncher.core.widget.CellContainer.onTouchEvent(CellContainer.java:207)
	at android.view.View.dispatchTouchEvent(View.java:8480)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
	at android.view.View.dispatchPointerEvent(View.java:8675)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
	at android.os.MessageQueue.next(<Xposed>)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by BennyKok** [comment]
so it works before the update?

**Comment by dkanada** [comment]
@BennyKok I have been away from my desktop for a while but I think you added a new release recently, and I modified the gestures but have not yet added the custom dialog for gestures back in. I was going to add the dialog to the minibar as well and add more custom actions, hence the changes.

**Comment by iknownothingaboutcomputers** [comment]
@BennyKok Yes, it was working fine before the update. Sorry for the super late reply.

**Comment by gsantner** [comment]
@iknownothingaboutcomputers State on current version?

**Comment by iknownothingaboutcomputers** [comment]
@gsantner Sorry for the late reply. I get no notifs fo replies received. Anyway, current state is that when I press 'Launch App' in 'Gestures', nothing happens. Before, the list of apps would open but now even that doesn't happen. This happens for every Gesture (Double tap to Unpinch).

Using Version 0.5.8 (alpha).

**Comment by just-Nob** [comment]
I can reproduce that misbehavior as well.
Nothing happens when trying to attach an app to a gesture.

**Comment by dkanada** [comment]
should be fixed
