### ISSUE TITLE
Cyclic crash

### ISSUE THREAD

**Issue by axet** [OpenLauncherTeam/openlauncher#260]
Would be nice, if Crash dialog should clear app defaults (default app to open home screen, so I can start another launcher and continue to work with a device)

```
Build version: 0.5.5 
Build date: 1979-11-30 00:00:00 
Current date: 2017-10-06 12:01:48 
Device: HTC Nexus 9 
 
Stack trace:  
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:533)
	at java.lang.Integer.parseInt(Integer.java:556)
	at com.benny.openlauncher.core.util.DatabaseHelper.getSelection(DatabaseHelper.java:285)
	at com.benny.openlauncher.core.util.DatabaseHelper.getDock(DatabaseHelper.java:174)
	at com.benny.openlauncher.core.widget.Dock.initDockItem(Dock.java:54)
	at com.benny.openlauncher.core.activity.Home$5.onAppUpdated(Home.java:316)
	at com.benny.openlauncher.util.AppManager.notifyUpdateListeners(AppManager.java:195)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:295)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening

**Comment by axet** [comment]
yes, it is still happening.

**Comment by gsantner** [comment]
version?

**Comment by axet** [comment]
recent from play store. it saying 0.5.8(alpha)

**Comment by axet** [comment]
Build version: 0.5.8(alpha) 
Build date: 1979-11-30 00:00:00 
Current date: 2018-01-14 20:43:57 
Device: HTC Nexus 9 
 
Stack trace:  
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:533)
	at java.lang.Integer.parseInt(Integer.java:556)
	at com.benny.openlauncher.core.util.DatabaseHelper.getSelection(DatabaseHelper.java:285)
	at com.benny.openlauncher.core.util.DatabaseHelper.getDock(DatabaseHelper.java:174)
	at com.benny.openlauncher.core.widget.Dock.initDockItem(Dock.kt:36)
	at com.benny.openlauncher.core.activity.CoreHome$initAppManager$1.onAppUpdated(CoreHome.kt:584)
	at com.benny.openlauncher.util.AppManager.notifyUpdateListeners(AppManager.kt:160)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.kt:247)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.kt:191)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by gsantner** [comment]
I would suggest to just delete OpenLaunchers App Data (in systemsettings) - there seem to be some corrupt data in the database.
