### ISSUE TITLE
Crash when unlocking screen

### ISSUE THREAD

**Issue by ehussong** [OpenLauncherTeam/openlauncher#278]
#### General information

* **App version:**
0.5.5
* **Android Version:**
7.0

#### Expected result
**What is expected?** 
Screen unlocks to homepage

**What does happen instead?**
Screen unlocked then immediately opened to bug report before loading home page

#### Steps to reproduce
Happens occasionally. Difficult to reproduce, but always seems to happen when unlocking screen when it does happen.

OpenLauncher

Build version: 0.5.5 
Build date: 1979-11-29 18:00:00 
Current date: 2017-10-24 10:06:18 
Device: Google Pixel XL 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.android.internal.util.VirtualRefBasePtr.get()' on a null object reference
	at android.view.RenderNodeAnimator.applyInterpolator(RenderNodeAnimator.java:171)
	at android.view.RenderNodeAnimator.start(RenderNodeAnimator.java:185)
	at com.benny.openlauncher.core.widget.AppDrawerController$4.run(AppDrawerController.java:150)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1127)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by ab-iman** [comment]
I see exactly the same stack trace.  Happened once in 2 days of usage. I believe I unlocked using the fingerprint sensor – not sure if that matters.

Build version: 0.5.5 
Build date: 1979-11-29 16:00:00 
Current date: 2017-11-08 09:57:29 
Device: Huawei Nexus 6P

**Comment by ehussong** [comment]
Sometimes it happens once a week. Sometimes 3-4 times within an hour.

**Comment by gsantner** [comment]
From the log it seems not to be related to OpenLaunchers code.

Closing as inactive (OR done) - reopen/comment if needed or if this is still happening on latest version
