### ISSUE TITLE
ISSUES : FIX LATER

### ISSUE THREAD

**Issue by BennyKok** [OpenLauncherTeam/openlauncher#281]
This is a list of issues that are going to fix later, not at the moment and to organize all the issues. As we need to port most of the code to Kotlin first. (I will keep on rearrange others issues as well)

You may wonder why I am doing this??? A lot of issues is out there and most of them were interconnected, this centralize all kinds of problems and hope to point out a clear path to fixing all the issues. While we can focus on refactoring most of the code into Kotlin, some issues maybe fixed somehow. So please help by keep tracking new update and testing out the errors.

## General

**Layout Improvements:**
#63 (padding) #120 (rotation) #166 (layout messed up -> database problem?)

**App Shortcut Improvements:**
#60 (item vanish)

**Widget Improvements:**
#30 (scaling) #59 (placement) #110 (remove padding) #111 (drag n drop) #121 (picker preview)

**Folder Improvements:**
#32 (usability) #44  (folder order)

**Styling Improvements:**
#49 (Status bar color) #105 (per app customization) #106 (Icon packs) #122 (normalize icon)

**UI Improvements:**
#35 (drawer scroll bar) #52 (drawer show others app) #58 (item option menu : drag n drop) 

**Usability Improvements:**
#66 (hiding apps) #73 (item rearranging) #102 (home button action) #123 (when app update ->update icons) #148 (sound & vibration) #173 (pages drag n drop)

**More features:**
#50 (Action covers) #165 (Notification badges) #82 (app shortcut)

## Crashes 
#164 #161 #157 (opening app) #154 (moving items) #161 (adding item)

## Implementing unit test
#128

**Comment by kwrnel** [comment]
Build version: 0.5.5 
Build date: 1980-01-01 00:00:00 
Current date: 2017-11-07 00:28:27 
Device: Xiaomi Redmi 4A 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.benny.openlauncher.core.widget.Desktop.initDesktopNormal(com.benny.openlauncher.core.activity.Home)' on a null object reference
	at com.benny.openlauncher.core.activity.Home$6.onAppDeleted(Home.java:326)
	at com.benny.openlauncher.util.AppManager.notifyRemoveListeners(AppManager.java:205)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:299)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.access$500(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by gsantner** [comment]
Removed comment of others and marking this as maintainer only.

**Comment by gsantner** [comment]
guess this wont happen

**Comment by gsantner** [comment]
guess this wont happen
