### ISSUE TITLE
Continuous crashing after reboot and all the icons on the second page duplicated

### ISSUE THREAD

**Issue by ArielLilly** [OpenLauncherTeam/openlauncher#284]
Build version: 0.5.3 
Build date: 1980-01-01 00:00:00 
Current date: 2017-11-20 22:45:08 
Device: BLU Vivo XL2 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
	at com.benny.openlauncher.util.AppManager.findApp(AppManager.java:61)
	at com.benny.openlauncher.viewutil.GroupIconDrawable.<init>(GroupIconDrawable.java:46)
	at com.benny.openlauncher.widget.AppItemView$Builder.setGroupItem(AppItemView.java:226)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:85)
	at com.benny.openlauncher.widget.Desktop.addItemToPage(Desktop.java:281)
	at com.benny.openlauncher.widget.Desktop.initDesktopNormal(Desktop.java:102)
	at com.benny.openlauncher.activity.Home$3.onAppUpdated(Home.java:237)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:221)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:716)

**Comment by BennyKok** [comment]
The version you are using is outdated, the latest version should be fixed the crashing after reboot.

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
