### ISSUE TITLE
Crash loop after exiting ultra power saver mode

### ISSUE THREAD

**Issue by ahirschberg** [OpenLauncherTeam/openlauncher#285]
#### General information

* **App version:**
0.5.5
* **Android Version:**
7.0
#### Expected result
**What is expected?** 
The app does not continually crash.

**What does happen instead?**
The app crashes immediately on opening

```
Build version: 0.5.5 
Build date: 1980-01-01 00:00:00 
Current date: 2017-11-23 09:48:24 
Device: Samsung SM-G935V 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.benny.openlauncher/com.benny.openlauncher.activity.Home}: java.lang.NumberFormatException: For input string: ""
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4974)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6688)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:533)
	at java.lang.Integer.parseInt(Integer.java:556)
	at com.benny.openlauncher.core.util.DatabaseHelper.getSelection(DatabaseHelper.java:285)
	at com.benny.openlauncher.core.util.DatabaseHelper.getDesktop(DatabaseHelper.java:156)
	at com.benny.openlauncher.core.widget.Desktop.init(Desktop.java:145)
	at com.benny.openlauncher.core.activity.Home.initViews(Home.java:212)
	at com.benny.openlauncher.activity.Home.initViews(Home.java:139)
	at com.benny.openlauncher.core.activity.Home.init(Home.java:186)
	at com.benny.openlauncher.core.activity.Home.onCreate(Home.java:144)
	at com.benny.openlauncher.activity.Home.onCreate(Home.java:85)
	at android.app.Activity.performCreate(Activity.java:6912)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
	... 10 more
```
#### Steps to reproduce
* Exit ultra power save
* Interact with a Homescreen element (folder?) before the launcher has fully loaded
* Observe crashes

**Comment by BennyKok** [comment]
@dkanada  , database problem, was this fixed?

**Comment by dkanada** [comment]
It looks like we just need to add some kind of check before the database is queried with an empty string or maybe return a null value. The error probably means the folder wasn't loaded yet so it didn't have a value to pass to the DatabaseHelper class.

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening
