### ISSUE TITLE
Crash since last update

### ISSUE THREAD

**Issue by Chamblard** [OpenLauncherTeam/openlauncher#295]
If you are reporting crashes or expected behaviour then please check if all requirements are fulfilled otherwise the issue will be closed without any comment

  * Add details to fields  below
  * Use search. Check if the issue is already reported before creating a new one. 
    https://github.com/OpenLauncherTeam/openlauncher/issues
  * Don't report update problems. Note that the OL Team is working on the core features and breaking changes may occur. We try to keep the amount of legacy code low. Try to reset app before posting.
  * Delete this info block
-----------------------------

#### General information

* **App version: 0.58 (alpha)**
* **Android Version: 7.1.1**

#### Expected result
**What is expected : go to app menu or go to right tab** 

**What does happen instead : Crash !! **

#### Steps to reproduce
* go right from home screen
* go to app menu

**Comment by fungs** [comment]
Same here, after an accidental update the launcher crashes when it starts and the installation of the stable version fails under android 7.1

**Comment by gsantner** [comment]
We cannot help without any logs or like that. I can only suggest you to reset openlaunchers's appdata via system settings -> Apps

**Comment by fungs** [comment]
Since I couldn't go back to the old version (package re-installation failure), resetting the app data helped but of course you have to start from the scratch, again.

**Comment by Chamblard** [comment]
Build version: 0.5.5 
Build date: 1979-11-30 01:00:00 
Current date: 2018-01-18 15:10:01 
Device: Sony F8331 
 
Stack trace:  
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4915)
	at android.view.ViewGroup.addView(ViewGroup.java:4746)
	at android.view.ViewGroup.addView(ViewGroup.java:4686)
	at android.view.ViewGroup.addView(ViewGroup.java:4659)
	at com.benny.openlauncher.core.widget.CellContainer.addView(CellContainer.java:437)
	at com.benny.openlauncher.core.widget.CellContainer.addViewToGrid(CellContainer.java:454)
	at com.benny.openlauncher.core.widget.Desktop.revertLastItem(Desktop.java:379)
	at com.benny.openlauncher.core.widget.DragOptionView.onDragEvent(DragOptionView.java:312)
	at android.view.View.callDragEventHandler(View.java:23069)
	at android.view.View.dispatchDragEvent(View.java:23057)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1636)
	at com.benny.openlauncher.core.widget.DragOptionView.dispatchDragEvent(DragOptionView.java:213)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1624)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1624)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1624)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1624)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1624)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1624)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5959)
	at android.view.ViewRootImpl.-wrap8(Unknown Source:0)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3956)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:251)
	at android.app.ActivityThread.main(ActivityThread.java:6563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)



Cordialement, 

Martin BLANCHARD
06.79.52.85.16
