### ISSUE TITLE
App Crashes When I Want To See List Of Apps

### ISSUE THREAD

**Issue by nasrabadiAM** [OpenLauncherTeam/openlauncher#327]
#### General information

* **App version:**0.5.8(alpha) from playstore
* **Android Version:**7.0 
* **Device:**LG-H990ds

#### Expected result
**What is expected?** 
show list of installed apps.

**What does happen instead?**
crash screen will be shown.

Logcat:
```
01-31 11:26:12.576 32472-32490/? E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                              at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                              at java.lang.Thread.run(Thread.java:761)
                                                           Caused by: java.lang.OutOfMemoryError: Failed to allocate a 67108876 byte allocation with 18527576 free bytes and 17MB until OOM
                                                              at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                              at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                              at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
                                                              at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
                                                              at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1152)
                                                              at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:855)
                                                              at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:706)
                                                              at android.content.res.Resources.getDrawable(Resources.java:776)
                                                              at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1040)
                                                              at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:2386)
                                                              at android.app.ApplicationPackageManager.loadItemIcon(ApplicationPackageManager.java:2366)
                                                              at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:223)
                                                              at android.content.pm.ComponentInfo.loadDefaultIcon(ComponentInfo.java:222)
                                                              at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:2389)
                                                              at android.app.ApplicationPackageManager.loadItemIcon(ApplicationPackageManager.java:2366)
                                                              at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:223)
                                                              at android.content.pm.ResolveInfo.loadIcon(ResolveInfo.java:248)
                                                              at com.benny.openlauncher.util.AppManager$App.<init>(AppManager.java:320)
                                                              at com.benny.openlauncher.util.AppManager$AsyncGetApps.doInBackground(AppManager.java:262)
                                                              at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                              at java.lang.Thread.run(Thread.java:761) 
```
#### Steps to reproduce
*
1-open menu of open launcher.
2-click on apps button.
3-crash will be produced.

Notice: I have more than 600 apps installed on my device.

**Comment by BennyKok** [comment]
this is somehow an out of memory error due to getting all the apps in the background, somedays we should come up with a better solution. But I still need to test this out as I there are some code changes in the previous week that I havent checked out

**Comment by fail0** [comment]
I have the same issue, but with only about 15 apps installed (Android 7.0 using latest from F-Droid).

**Comment by fail0** [comment]
Actually, the issue for me was not having OpenLauncher set as my default (and then not setting it as my default because of the issue). Sorry!

**Comment by just-Nob** [comment]
Hi @nasrabadiAM,
what do you mean by saying "when I want to see list of apps"? Do you mean "when opening app drawer"?
If so, I've the same issue. It came up a few days ago, I guess after installing some apps, because it worked before. I have to check this.

**Comment by just-Nob** [comment]
Anyway, if so, this seems to be related to the #325.

**Comment by just-Nob** [comment]
Hi @fail0,

if you want to have a temporary replacement for the app drawer until the integrated drawer will be fixed, just have a look to some tools that you're able to find in F-Droid repo by searching for "app launcher".

You'll find some launchers there that will not only register themselves as a launcher, but also can be launched like a "normal standard app" from your standard launcher, i.e. from OpenLauncher as well. :wink:

My favorite is "Hayai Launcher", which is pretty small and doesn't need any access rights. If configured in the settings, it can also be launched from the status bar, and the sorting order can be configured as well.

But there are still some other suitable apps, like LaunchTime or Apps2Org, that can be used.
