### ISSUE TITLE
Crash. During "search" and app switching.

### ISSUE THREAD

**Issue by serebryakov-av** [OpenLauncherTeam/openlauncher#418]
1. Call "search" from side-bar.
2. Switch to other app and back.

Log:

Build version: 0.5.12 
Current date: 2018-10-10 17:53:30 
Device: OnePlus ONEPLUS A5000 
 
Stack trace:  
java.lang.RuntimeException: Unable to resume activity {com.benny.openlauncher/com.benny.openlauncher.activity.HomeActivity}: android.util.SuperNotCalledException: Activity {com.benny.openlauncher/com.benny.openlauncher.activity.HomeActivity} did not call through to super.onResume()
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3726)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3766)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6753)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: android.util.SuperNotCalledException: Activity {com.benny.openlauncher/com.benny.openlauncher.activity.HomeActivity} did not call through to super.onResume()
	at android.app.Activity.performResume(Activity.java:7146)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3700)
	... 8 more

**Comment by dkanada** [comment]
Also happens when any setting is changed. I found an easy fix but we might want to find the root of the issue at some point.

**Comment by serebryakov-av** [comment]
I loaded last 3 commits (including be6ed91). Now changing "Show search string" setting didn't work. I have to restart launcher to apply this changing.

**Comment by serebryakov-av** [comment]
After a few minutes suddenly searchbar disappeared, but also turn on fullscreen-mode. Newertheless status bar didn't disappear.
![screenshot_20181011-110638](https://user-images.githubusercontent.com/443680/46789757-f0ba9f80-cd45-11e8-953a-4adb3b248878.png)

**Comment by dkanada** [comment]
Where is ''show search string'' in the settings? I wanna test it out now after the recent changes.

**Comment by serebryakov-av** [comment]
I wrote it wrong. Just the "Search Bar setting.
![screenshot_20181015-170055](https://user-images.githubusercontent.com/443680/46955687-30fa8480-d09c-11e8-8bfe-588111fbe58a.jpg)

**Comment by dkanada** [comment]
Ah okay, that was just fixed so this issue is gone now.
