### ISSUE TITLE
App Crashes when I delete apps from a folder

### ISSUE THREAD

**Issue by Fauli1221** [OpenLauncherTeam/openlauncher#446]
Build version: 0.6.0 
Build date: 1980-01-01 00:00:00 
Current date: 2018-11-03 07:14:02 
Device: Motorola Moto G Play 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewPropertyAnimator android.view.View.animate()' on a null object reference
	at com.benny.openlauncher.widget.Desktop.removeItem(Desktop.java:520)
	at com.benny.openlauncher.activity.HomeActivity.onRemoveItem(HomeActivity.java:393)
	at com.benny.openlauncher.activity.homeparts.HpDragOption$5.onClick(HpDragOption.java:375)
	at com.benny.openlauncher.activity.homeparts.HpDragOption$5.onClick(HpDragOption.java:360)
	at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:608)
	at com.mikepenz.fastadapter.utils.EventHookUtil$1.onClick(EventHookUtil.java:72)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22433)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by dkanada** [comment]
Is this a recurring issue or did it only happen once?

**Comment by dkanada** [comment]
I don't see any videos linked, did you forget to embed it?

**Comment by Fauli1221** [comment]
No I don't!
I try different way.

link:
https://mega.nz/#!VuRwzIxT
key:
!CyXq0cOwFJWq3SK7K7dv8W0opDalpXpnG_Z2i22hKH4

Am Mi., 7. Nov. 2018, 18:33 hat dkanada <notifications@github.com>
geschrieben:

**Comment by phanirithvij** [comment]
I have the same problem
This is the log

Build version: 0.6.1 
Build date: 1980-01-01 00:00:00 
Current date: 2019-06-01 10:07:42 
Device: Xiaomi Redmi Note 4 
 
Stack trace:  
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewPropertyAnimator android.view.View.animate()' on a null object reference
 at com.benny.openlauncher.widget.Desktop.removeItem(Desktop.java:520)
 at com.benny.openlauncher.activity.HomeActivity.onRemoveItem(HomeActivity.java:393)
 at com.benny.openlauncher.activity.homeparts.HpDragOption$5.onClick(HpDragOption.java:375)
 at com.benny.openlauncher.activity.homeparts.HpDragOption$5.onClick(HpDragOption.java:360)
 at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:608)
 at com.mikepenz.fastadapter.utils.EventHookUtil$1.onClick(EventHookUtil.java:72)
 at android.view.View.performClick(View.java:5619)
 at android.view.View$PerformClick.run(View.java:22298)
 at android.os.Handler.handleCallback(Handler.java:754)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:165)
 at android.app.ActivityThread.main(ActivityThread.java:6375)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```
