### ISSUE TITLE
Cannot add contact shortcuts to home screen

### ISSUE THREAD

**Issue by benoitmasson** [OpenLauncherTeam/openlauncher#448]
#### General information

* **App version:** 0.6.0
* **System:** Lineage 14.1 (Android 7.1.2) on Samsung Galaxy S4 LTE

#### Description

When on the contact screen I select the “Place on Home screen” menu item, I see a popup confirmation that it has been done, but when I return to my home screen, nothing has happened (I would expect a shortcut for the contact to be created).

Not sure whether this is launcher-related though…

#### Logs

```11-07 14:05:43.171 10809 12064 E ContactLoader: loadInBackground=content://com.android.contacts/contacts/lookup/<uuid>..vcf/1128
11-07 14:05:43.333 10809 12063 E ContactLoader: loadInBackground=content://com.android.contacts/contacts/lookup/<uuid>..vcf/1128
11-07 14:05:43.403 10809 10809 I ContactLoader: Registering content observer for content://com.android.contacts/contacts/lookup/<uuid>..vcf/1128
11-07 14:05:43.462   919  1269 W System.err: java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
11-07 14:05:43.463   919  1269 W System.err: 	at com.android.internal.telephony.UiccPhoneBookController.getIccPhoneBookInterfaceManager(UiccPhoneBookController.java:181)
11-07 14:05:43.463   919  1269 W System.err: 	at com.android.internal.telephony.UiccPhoneBookController.getAdnRecordsCapacityForSubscriber(UiccPhoneBookController.java:140)
11-07 14:05:43.463   919  1269 W System.err: 	at com.android.internal.telephony.IIccPhoneBook$Stub.onTransact(IIccPhoneBook.java:216)
11-07 14:05:43.463   919  1269 W System.err: 	at android.os.Binder.execTransact(Binder.java:565)
11-07 14:05:45.396  1551  1551 I         : createItem: Afficher le contact (ID: -720654529)
11-07 14:05:45.478  1551  1551 D         : Shortcut installed - John Doe => Intent: Intent { act=android.provider.action.QUICK_CONTACT dat=content://com.android.contacts/contacts/lookup/<uuid>..vcf/1128 typ=vnd.android.cursor.item/contact flg=0x10018000 (has extras) } (Item _type: APP; x = 0, y = 0, added = false)
11-07 14:05:45.492  1551  1551 I         : createItem: Afficher le contact (ID: -1799453996)
11-07 14:05:45.538  1551  1551 D         : Shortcut installed - John Doe => Intent: Intent { act=android.provider.action.QUICK_CONTACT dat=content://com.android.contacts/contacts/lookup/<uuid>..vcf/1128 typ=vnd.android.cursor.item/contact flg=0x10018000 (has extras) } (Item _type: APP; x = 0, y = 0, added = false)
11-07 14:05:45.662 10809 10843 D OpenGLRenderer: endAllActiveAnimators on 0x9b4c5a80 (MenuPopupWindow$MenuDropDownListView) with handle 0x99908300
```

**Comment by dkanada** [comment]
I am aware of the issue, shortcuts need a lot of work.

you can track any progress at #355
