### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hamed1987** [OpenLauncherTeam/openlauncher#454]
Build version: 0.5.8(alpha) 
Build date: 1979-11-30 00:00:00 
Current date: 2018-11-28 13:15:48 
Device: HMD Global TA-1053 
 
Stack trace:  
java.lang.StringIndexOutOfBoundsException: length=12; index=13
	at java.lang.String.substring(String.java:1971)
	at com.benny.openlauncher.core.widget.AppItemView.onDraw(AppItemView.java:196)
	at android.view.View.draw(View.java:19233)
	at android.view.View.updateDisplayListIfDirty(View.java:18183)
	at android.view.View.draw(View.java:18961)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4247)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4607)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4033)
	at android.view.View.draw(View.java:19236)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4013)
	at android.view.View.updateDisplayListIfDirty(View.java:18183)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4231)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4211)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3006)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2810)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2363)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1396)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6773)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:974)
	at android.view.Choreographer.doCallbacks(Choreographer.java:786)
	at android.view.Choreographer.doFrame(Choreographer.java:721)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by dkanada** [comment]
That version has been updated three times by now I think, it was also fixed two versions ago. Can you update and tell me if that fixes your problem?

**Comment by hamed1987** [comment]
hi
i installed last version from google play

**Comment by gsantner** [comment]
We dont have control over the app id on gplay and the owner (benny) is not active in this project anymore
