### ISSUE TITLE
Crash after uninstalling app

### ISSUE THREAD

**Issue by Catfriend1** [OpenLauncherTeam/openlauncher#458]
#### General Information

* **OpenLauncher Version:** Most recent fdroid version
* **Android Version:** 8.1.0
* **Custom ROM:** no, Xiaomi MIUI 10
* **Install Source:** F-Droid

#### Description
Uninstalled the app "editor" from fdroid while being in fdroid app . Then returning to home screen where the app was never added to and the big icon appeared. Restart doesn't revive openlauncher, cannot open any new app. Openlauncher worked fine for months until now. Will post the version when near a computer, it's the most recent fdroid version.

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.
Build version: 0.6.1 
Build date: 1979-11-30 01:00:00 
Current date: 2018-12-06 17:02:43 
Device: Xiaomi MI 8 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.putAll(android.os.Bundle)' on a null object reference
	at android.os.Parcel.readException(Parcel.java:2011)
	at android.os.Parcel.readException(Parcel.java:1951)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetOptions(IAppWidgetService.java:711)
	at android.appwidget.AppWidgetManager.updateAppWidgetOptions(AppWidgetManager.java:533)
	at com.benny.openlauncher.viewutil.ItemViewFactory.updateWidgetOption(ItemViewFactory.java:254)
	at com.benny.openlauncher.viewutil.ItemViewFactory.access$000(ItemViewFactory.java:27)
	at com.benny.openlauncher.viewutil.ItemViewFactory$5.run(ItemViewFactory.java:125)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6648)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)
!--

Look for already reported issues before posting! If the issue doesn't exist please give as much information as possible, including what happens versus exactly what you expect to happen in that situation. Screenshots or videos are always helpful for UI issues.

-->

**Comment by Catfriend1** [comment]
Workaround: Rebooted the phone and openlauncher worked again.
What did not help: force closing openlauncher, reverting to mi launcher, setting openlauncher again (before the reboot)
Openlauncher 0.6.1

**Comment by dkanada** [comment]
Did you have a widget on your desktop somewhere for this app?

**Comment by Catfriend1** [comment]
No, I just installed it from fdroid, did not even go to the home screen and launched it directly from the store, saw I don't want that app and hit uninstall. https://github.com/OpenLauncherTeam/openlauncher/issues/445 maybe related as I have widgets that were not loading since a long time ago (more weeks)

**Comment by gsantner** [comment]
cannot reproduce on current release.

**Comment by Catfriend1** [comment]
Thanks for looking into it. :-)

**Comment by gsantner** [comment]
NP

**Comment by planetloli** [comment]
please delete issue
