### ISSUE TITLE
Long pressing widgets crashes launcher.

### ISSUE THREAD

**Issue by wilmarcdw** [OpenLauncherTeam/openlauncher#461]
#### General Information

* **OpenLauncher Version:** 0.6.1-nightly-181223 
* **Android Version:** 8.1.0
* **Custom ROM:** AospExtended 5.7
* **Install Source:** F-Droid

#### Description

Long-pressing any widget added to the desktop causes the launcher to crash.
Any widget, be it weather (OmniJaws), Clock (OmniClock), calc, calendar, search bar, etc.
Note that this build is apparently from the Nanolx F-Droid Repo so I wasn't sure if it was okay to open an issue.
There are some similarities with other issues regarding widgets but didn't notice anything about long presses.

Additional items - LG G3 D851, microG (NanoDroid), Xposed Framework

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

Build version: 0.6.1-nightly-181223 
Build date: 1979-11-30 00:00:00 
Current date: 2018-12-27 02:48:24 
Device: LGE LG-D851 
 
Stack trace:  
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to com.benny.openlauncher.widget.CellContainer$LayoutParams
	at com.benny.openlauncher.widget.CellContainer.removeView(CellContainer.java:405)
	at com.benny.openlauncher.widget.Desktop.setLastItem(Desktop.java:368)
	at com.benny.openlauncher.util.DragHandler.startDrag(DragHandler.java:24)
	at com.benny.openlauncher.util.DragHandler$1.onLongClick(DragHandler.java:37)
	at com.benny.openlauncher.widget.WidgetView.onInterceptTouchEvent(WidgetView.java:37)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2511)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3352)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
	at android.view.View.dispatchPointerEvent(View.java:12015)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4819)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4633)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4171)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4224)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4190)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4317)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4198)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4374)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4171)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4224)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4190)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4198)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4171)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6692)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6666)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6627)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6795)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6766)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6818)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:652)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:442)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

<!--

->

**Comment by dkanada** [comment]
I wasn't aware of a nightly build being used anywhere, can you point me towards the repository? I think the master branch is broken right now, I wouldn't have done so if I knew some people were using a nightly version :)

**Comment by wilmarcdw** [comment]
After getting the address for the repo I was reminded that NanoDroid makes use of unofficial builds of some apps (OpenLauncher, OmniJAWS, Amaze file manager to name a few). I didn't think to ask in the NanoDroid thread if anyone else was having issues with the launcher.
Anyhind, here's the repo info page which has links to the launcher source used.

http://nanolx.org/fdroid/repo/

**Comment by wilmarcdw** [comment]
Nanolx, yeah I realized that when I looked at the diff file.
And thanks for correcting me about Amaze. I was thinking back aways. (^o^).

I reckon I should close this one.
