### ISSUE TITLE
Crash when adding Home-assistant widget

### ISSUE THREAD

**Issue by agilob** [OpenLauncherTeam/openlauncher#499]
#### General Information

* **OpenLauncher Version:** 0.7.0
* **Android Version:** 6
* **Custom ROM:** Motorola
* **Install Source:** F-Droid

#### Description
When attempting to add home assistant widget OL crashes:

#### Log

```
Stack trace:  
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=25717, result=-1, data=null} to activity {com.benny.openlauncher/com.benny.openlauncher.activity.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4130)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4173)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
	at com.benny.openlauncher.activity.HomeActivity.createWidget(HomeActivity.java:550)
	at com.benny.openlauncher.activity.HomeActivity.onActivityResult(HomeActivity.java:577)
	at android.app.Activity.dispatchActivityResult(Activity.java:6946)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)
	... 9 more
```

**Comment by dkanada** [comment]
These widgets keep haunting me don't they. I thought this crash had been fixed.

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
