### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by hobleyd** [OpenLauncherTeam/openlauncher#519]
Is anyone else seeing this crash sporadically?

Build version: 0.7.0 
Current date: 2019-11-10 06:17:53 
Device: HUAWEI VOG-L29 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'com.benny.openlauncher.widget.Desktop com.benny.openlauncher.activity.HomeActivity.getDesktop()' on a null object reference
	at com.benny.openlauncher.widget.WidgetContainer.updateWidgetOption(WidgetContainer.java:129)
	at com.benny.openlauncher.viewutil.ItemViewFactory$2.run(ItemViewFactory.java:139)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by gsantner** [comment]
Sometimes desktop doesn't render any apps/icons for me..need to check when seeing next time. maybe related to this

**Comment by hobleyd** [comment]
Yes - when this does happen, the desktop doesn't render any apps/icons for me either (briefly until the crash screen is displayed).
