### ISSUE TITLE
[crash] opening folder containing a single app

### ISSUE THREAD

**Issue by joeftiger** [OpenLauncherTeam/openlauncher#524]
#### General Information

* **OpenLauncher Version:** 0.7.1
* **Android Version:** 10.0
* **Custom ROM:** None (MIUI 11 EEA)
* **Install Source:** F-Droid

#### Description
I created a folder with 2 apps. One app got uninstalled on boot. 

Opening the folder crashes OpenLauncher immediately. 

It's expected to either show a folder containing only one app or automatically disband the folder into the single app launcher.

#### Log
Build version: 0.7.1 
Build date: 1979-11-30 01:00:00 
Current date: 2019-11-27 07:15:18 
Device: Xiaomi MI 9 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnLongClickListener(android.view.View$OnLongClickListener)' on a null object reference
	at com.benny.openlauncher.widget.GroupPopupView.showPopup(GroupPopupView.java:119)
	at com.benny.openlauncher.widget.AppItemView$Builder$3.onClick(AppItemView.java:222)
	at android.view.View.performClick(View.java:7160)
	at android.view.View.performClickInternal(View.java:7137)
	at android.view.View.access$3500(View.java:810)
	at android.view.View$PerformClick.run(View.java:27418)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:221)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

#### Additional
I'll _try_ to find the issue in the source code later on.

**Comment by joeftiger** [comment]
Relates to #523
