### ISSUE TITLE
Crash on fresh install

### ISSUE THREAD

**Issue by shawn1thompson** [OpenLauncherTeam/openlauncher#533]
#### General Information

* **Android Version:** 9
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description
Crashes immediately upon start, fresh install, cleared cache and data from previous installs

#### Log

Build version: 0.7.2 
Build date: 1979-11-29 18:00:00 
Current date: 2019-12-03 21:12:17 
Device: Motorola moto g(6) 
 
Stack trace:  
java.lang.NullPointerException: class name is null
	at android.content.ComponentName.<init>(ComponentName.java:102)
	at android.content.Intent.setClassName(Intent.java:9215)
	at com.benny.openlauncher.util.Tool.getIntentFromApp(Tool.java:222)
	at com.benny.openlauncher.model.Item.newAppItem(Item.java:50)
	at com.benny.openlauncher.widget.SearchBar$5.onAppUpdated(SearchBar.java:247)
	at com.benny.openlauncher.util.AppManager.notifyUpdateListeners(AppManager.java:123)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:219)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:215)
	at android.app.ActivityThread.main(ActivityThread.java:6939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by gsantner** [comment]
still happens?
