### ISSUE TITLE
Stacktrace in Android 10

### ISSUE THREAD

**Issue by matfechner** [OpenLauncherTeam/openlauncher#543]
#### General Information

* **OpenLauncher Version:** 0.7.2
* **Android Version:** 10
* **Custom ROM:** Android One
* **Install Source:** F-Droid

#### Description

Build version: 0.7.2
Build date: 1979-11-30 01:00:00
Current date: 2019-12-18 07:39:26
Device: HMD Global Nokia 7.1

Stack trace:
java.lang.NullPointerException: class name is null
at android.content.ComponentName.<init>(ComponentName.java:103)
at android.content.Intent.setClassName(Intent.java:9708)
at com.benny.openlauncher.util.Tool.getIntentFromApp(Tool.java:222)
at com.benny.openlauncher.model.Item.newAppItem(Item.java:50)
at com.benny.openlauncher.widget.SearchBar$5.onAppUpdated(SearchBar.java:247)
at com.benny.openlauncher.util.AppManager.notifyUpdateListeners(AppManager.java:123)
at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:219)
at android.os.AsyncTask.finish(AsyncTask.java:755)
at android.os.AsyncTask.access$900(AsyncTask.java:192)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7397)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

**Comment by mattfilix** [comment]
i've find out  the version  0.7.1 works. 
Before i've updated to Android 10 i've had two Desktops
but this feature wont work under Android 10

**Comment by gsantner** [comment]
closing as said to work. I also use OL on Android 10 and have no issue.
