### ISSUE TITLE
Crash while trying to open app

### ISSUE THREAD

**Issue by deafwhippin** [OpenLauncherTeam/openlauncher#565]
Build version: 0.7.2 
Build date: 1979-11-29 19:00:00 
Current date: 2020-01-21 20:01:30 
Device: Motorola moto z3 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnLongClickListener(android.view.View$OnLongClickListener)' on a null object reference
	at com.benny.openlauncher.widget.GroupPopupView.showPopup(GroupPopupView.java:119)
	at com.benny.openlauncher.widget.AppItemView$Builder$3.onClick(AppItemView.java:222)
	at android.view.View.performClick(View.java:6618)
	at android.view.View.performClickInternal(View.java:6590)
	at android.view.View.access$3100(View.java:781)
	at android.view.View$PerformClick.run(View.java:25945)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by MorgothSauron** [comment]
I have the same problem. For me the application will crash every time I try to open an application group on the main screen. I was using a different launcher before and I suspect that this group has a reference to an application that I deleted. It will crash every single time

```
Build version: 0.7.2
Build date: 1979-11-30 01:00:00
Current date: 2020-04-16 15:45:07
Device: Xiaomi Redmi Note 8 Pro

Stack trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnLongClickListener(android.view.View$OnLongClickListener)' on a null object reference
at com.benny.openlauncher.widget.GroupPopupView.showPopup(GroupPopupView.java:119)
at com.benny.openlauncher.widget.AppItemView$Builder$3.onClick(AppItemView.java:222)
at android.view.View.performClick(View.java:6614)
at android.view.View.performClickInternal(View.java:6587)
at android.view.View.access$3100(View.java:787)
at android.view.View$PerformClick.run(View.java:26122)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6831)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
```

**Comment by misieck** [comment]
I can confirm this bug. Crashes when opening a folder with an app that has been deleted.

**Comment by gsantner** [comment]
might be fixed already.
