### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tex** [OpenLauncherTeam/openlauncher#606]
#### General Information

* **OpenLauncher Version:** 0.7.3 (41)
* **Android Version:** 6
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Log

This is only needed for crashes or other issues you notice in your system logs from OpenLauncher.

Build version: 0.7.3 
Build date: 1980-01-01 00:00:00 
Current date: 2020-07-12 10:34:36 
Device: Motorola MotoG3 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.benny.openlauncher.activity.HomeActivity.onStartApp(android.content.Context, com.benny.openlauncher.model.App, android.view.View)' on a null object reference
	at com.benny.openlauncher.util.Tool.startApp(Tool.java:155)
	at com.benny.openlauncher.widget.AppItemView$Builder$1$1.run(AppItemView.java:201)
	at com.benny.openlauncher.util.Tool$4$1.run(Tool.java:109)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by gsantner** [comment]
probably fixed
