### ISSUE TITLE
Meteogram Widget crash

### ISSUE THREAD

**Issue by Xnyle** [OpenLauncherTeam/openlauncher#615]
#### General Information

* **OpenLauncher Version:** 0.7.3
* **Android Version:** 10
* **Custom ROM:** Posp
* **Install Source:** F-Droid

#### Description
Trying to add Meteogram Weather Widget (pub:Benny Wydooghe) Results in the following Stacktrace

#### Log

Build version: 0.7.3 
Build date: 1979-11-30 01:00:00 
Current date: 2020-09-02 19:51:28 
Device: Xiaomi Redmi Note 8 Pro 
 
Stack trace:  
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=25717, result=-1, data=null} to activity {com.benny.openlauncher/com.benny.openlauncher.activity.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
	at com.benny.openlauncher.activity.homeparts.HpDesktopOption.createWidget(HpDesktopOption.java:86)
	at com.benny.openlauncher.activity.HomeActivity.onActivityResult(HomeActivity.java:489)
	at android.app.Activity.dispatchActivityResult(Activity.java:8135)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
	... 11 more

**Comment by gsantner** [comment]
Closing in favor of the Meta issue for Widgets #645 . Please have all discussion at that issue, including crashes, feature requests and more. I also lock this issue as there is nobody that wants to continue to reply on ~100+ mostly duplicate issues.  

Currently nobody is working on OpenLauncher Widgets code, so why **YOU** who reads this message, not steps up? :wink:
