### ISSUE TITLE
Xiaomi note 6 - Home - when pressing on files includes apps it crash and doesn't open

### ISSUE THREAD

**Issue by Meraki86** [OpenLauncherTeam/openlauncher#625]
#### General Information

* **OpenLauncher Version:** 0.7.2
* **Android Version:** 8.1
* **Custom ROM:** None
* **Install Source:** F-Droid

#### Description
I am a tester, i used this app for long time and found this bug today while i tried to add an app in a file at home, it didn't added and when i opened the file the app crashed, i captured a screenshot and got the logs.

#### Log

Build version: 0.7.2 
Build date: 1979-11-30 02:00:00 
Current date: 2020-10-14 09:35:12 
Device: Xiaomi Redmi Note 6 Pro 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnLongClickListener(android.view.View$OnLongClickListener)' on a null object reference
	at com.benny.openlauncher.widget.GroupPopupView.showPopup(GroupPopupView.java:119)
	at com.benny.openlauncher.widget.AppItemView$Builder$3.onClick(AppItemView.java:222)
	at android.view.View.performClick(View.java:6304)
	at android.view.View$PerformClick.run(View.java:24803)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

![Screenshot_2020-10-14-09-30-37-038_com benny openlauncher](https://user-images.githubusercontent.com/72855065/95959409-eda19080-0df1-11eb-880c-402cf530f075.png)

**Comment by gsantner** [comment]
reset openlauncher app data, should be gone then.
