### ISSUE TITLE
NullPointerException dragging widget

### ISSUE THREAD

**Issue by zeehio** [OpenLauncherTeam/openlauncher#64]
Hi,

Thanks for your work. I have started using your launcher and I love it.

I triggered a null pointer exception when I was moving a widget. I don't know exactly how to reproduce it, but I hope the stack trace can be useful to you.

```
Build version: 0.3.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-04-22 15:40:08 
Device: LGE Nexus 5X 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:84)
	at com.benny.openlauncher.widget.Desktop.addItemToPosition(Desktop.java:304)
	at com.benny.openlauncher.widget.Desktop.onDrag(Desktop.java:192)
	at android.view.View.callDragEventHandler(View.java:20898)
	at android.view.View.dispatchDragEvent(View.java:20889)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1510)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1492)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5551)
	at android.view.ViewRootImpl.-wrap7(ViewRootImpl.java)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

**Comment by BennyKok** [comment]
it is ok, I will fix that, give some times. Thanks. Oh so many issues, but don't have enough time.

**Comment by zeehio** [comment]
Another stack trace, this one is happening all the time since I changed the grid size in the app drawer settings to 6x6. As the launcher is crashing every time I don't have a trivial way to fix this (maybe I need to reset the launcher settings and data)

```
Build version: 0.3.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-04-24 11:32:11 
Device: LGE Nexus 5X 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=6; index=6
	at com.benny.openlauncher.widget.CellContainer.setOccupied(CellContainer.java:358)
	at com.benny.openlauncher.widget.CellContainer.addView(CellContainer.java:344)
	at com.benny.openlauncher.widget.CellContainer.addViewToGrid(CellContainer.java:366)
	at com.benny.openlauncher.widget.Desktop.addItemToPagePosition(Desktop.java:288)
	at com.benny.openlauncher.widget.Desktop.initDesktopItem(Desktop.java:99)
	at com.benny.openlauncher.activity.Home$3.onAppUpdated(Home.java:273)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:222)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by BennyKok** [comment]
I will try to fix some issue today as I finally got some time. Thx man.

**Comment by BennyKok** [comment]
Does that happen when you change to other grid size?

**Comment by zeehio** [comment]
I can't reproduce the last stack trace anymore. I just cleared all the data and cache because I needed to use the phone. Sorry for not being more detailed.

If there are crashes like this maybe it would be good to offer a couple of buttons in the RIP screen to "restore settings from last backup" or "reset openLauncher to default settings". A crash in the launcher is problematic because I usually use the launcher to open the settings screen to clear data and cache when an application is not working.

**Comment by BennyKok** [comment]
The rip screen is a library, I am not sure if I can add custom button. 
Really sorry for those crashes that make the launcher unusable, really sorry. Really sorry. I am trying to fix them now.

**Comment by zeehio** [comment]
Relax. I am still using your launcher and it works great! :-)

El dia 24 abr. 2017 5:06 p. m., "BennyKok" <notifications@github.com> va
escriure:

**Comment by BennyKok** [comment]
The second bug should be fixed so give it few more day to see if that still crash. 

Gonna fix others later.

**Comment by zeehio** [comment]
Can't reproduce the errors on 0.5.1. With all the code cleaning in widget positioning this must have been fixed. Thanks!
