### ISSUE TITLE
Crash after installation

### ISSUE THREAD

**Issue by beaver4** [OpenLauncherTeam/openlauncher#665]
#### General Information

* **OpenLauncher Version:** 220103
* **Android Version:** 5.1.1
* **Custom ROM:** None
* **Install Source:** built from source (master branch)
* **Device:** Google AVD

#### Description
App crashes immediately after start. It works fine on this commit https://github.com/OpenLauncherTeam/openlauncher/commit/513acc13cf6b78584bd7caeb5faa43ede74e40b0 Probably caused by 0ac9f7065d741174d1c967f2c89ba62b2d589a81

#### Log

```
Build version: 220103 
Build date: 1981-01-01 01:01:02 
Current date: 2022-01-03 22:46:56 
Device: Unknown Android SDK built for x86 
 
Stack trace:  
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.doInBackground(AppManager.java:185)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

#### Steps to reproduce bug

1. Install OpenLauncher 
2. Press HOME button

**Comment by gsantner** [comment]
@NetLagina can you please check this?

**Comment by beaver4** [comment]
I confirm the fix works.
