### ISSUE TITLE
Play store version crash

### ISSUE THREAD

**Issue by lawson85** [OpenLauncherTeam/openlauncher#675]
#### General Information

* **OpenLauncher Version:** 0.58 Alpha
* **Android Version:** 10
* **Custom ROM:** None: EMUI 10.0.0
* **Install Source:** Play store 

#### Log
Build version: 0.5.8(alpha) 
Build date: 1979-11-30 00:00:00 
Current date: 2022-04-20 18:25:39 
Device: HUAWEI HRY-LX1 
 
Stack trace:  
java.lang.StringIndexOutOfBoundsException: length=9; index=10
	at java.lang.String.substring(String.java:2060)
	at com.benny.openlauncher.core.widget.AppItemView.onDraw(AppItemView.java:196)
	at android.view.View.draw(View.java:21618)
	at android.view.View.updateDisplayListIfDirty(View.java:20483)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4607)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.draw(View.java:21621)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4013)
	at android.view.View.updateDisplayListIfDirty(View.java:20483)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.updateDisplayListIfDirty(View.java:20474)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.draw(View.java:21621)
	at android.view.View.updateDisplayListIfDirty(View.java:20483)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at io.codetail.widget.RevealFrameLayout.drawChild(RevealFrameLayout.java:32)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.draw(View.java:21621)
	at android.view.View.updateDisplayListIfDirty(View.java:20483)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.updateDisplayListIfDirty(View.java:20474)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.draw(View.java:21621)
	at android.view.View.updateDisplayListIfDirty(View.java:20483)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1367)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.updateDisplayListIfDirty(View.java:20474)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.updateDisplayListIfDirty(View.java:20474)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.updateDisplayListIfDirty(View.java:20474)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.updateDisplayListIfDirty(View.java:20474)
	at android.view.View.draw(View.java:21350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
	at android.view.View.draw(View.java:21621)
	at com.android.internal.policy.DecorView.draw(DecorView.java:964)
	at android.view.View.updateDisplayListIfDirty(View.java:20483)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3837)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3645)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2951)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1854)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8086)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
	at android.view.Choreographer.doFrame(Choreographer.java:776)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by lawson85** [comment]
This happens just after the intro screens, pressing home

**Comment by gsantner** [comment]
Nobody from devs have access to google play store entry.
