### ISSUE TITLE
Crash after changing icon pack

### ISSUE THREAD

**Issue by nazar-pc** [OpenLauncherTeam/openlauncher#707]
#### General Information

* **OpenLauncher Version:** 0.7.4 (debug build from ca6656a4d0d3280b03bfa40d4eb6996ac8ba3fb0)
* **Android Version:** 13
* **Custom ROM:** GrapheneOS
* **Install Source:** F-Droid

#### Description

It is sufficient to change icon pack to another one and most of the time (but not 100% of the time) it crashes when getting back to the home screen. After extra restart it works fine indefinitely.

#### Log

```
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.benny.openlauncher.widget.Desktop.getCurrentPage(Desktop.java:319)
	at com.benny.openlauncher.widget.WidgetContainer.updateWidgetOption(WidgetContainer.java:128)
	at com.benny.openlauncher.viewutil.ItemViewFactory$2.run(ItemViewFactory.java:144)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by gsantner** [comment]
OpenLauncher is not in active development. But feel free to make a merge request to fix the issue. Thank you.
