### ISSUE TITLE
Crash after font size change on MIUI 14

### ISSUE THREAD

**Issue by Catfriend1** [OpenLauncherTeam/openlauncher#715]
#### General Information

* **OpenLauncher Version:** 1.0.0
* **Android Version:** 13
* **Custom ROM:** xiaomi.eu stable 14
* **Install Source:** F-Droid?

#### Log

```
Build version: 1.0.0 
Current date: 2024-01-14 13:27:00 
Device: Xiaomi 2211133G 
 
Stack trace:  
java.lang.RuntimeException: Unable to destroy activity {com.benny.openlauncher/com.benny.openlauncher.activity.HomeActivity}: java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference in method 'android.util.SparseArray com.android.server.appwidget.AppWidgetServiceImpl$Host.getWidgetUids()'
	at android.app.ActivityThread.performDestroyActivity(Unknown Source:317)
	at android.app.ActivityThread.handleDestroyActivity(Unknown Source:0)
	at android.app.ActivityThread.handleRelaunchActivityInner(Unknown Source:37)
	at android.app.ActivityThread.handleRelaunchActivity(Unknown Source:343)
	at android.app.servertransaction.ActivityRelaunchItem.execute(Unknown Source:25)
	at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:76)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference in method 'android.util.SparseArray com.android.server.appwidget.AppWidgetServiceImpl$Host.getWidgetUids()'
	at android.os.Parcel.createExceptionOrNull(Unknown Source:25)
	at android.os.Parcel.createException(Unknown Source:0)
	at android.os.Parcel.readException(Unknown Source:11)
	at android.os.Parcel.readException(Unknown Source:10)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.stopListening(Unknown Source:27)
	at android.appwidget.AppWidgetHost.stopListening(Unknown Source:9)
	at com.benny.openlauncher.activity.HomeActivity.onDestroy(HomeActivity.java:567)
	at android.app.Activity.performDestroy(Unknown Source:57)
	at android.app.Instrumentation.callActivityOnDestroy(Unknown Source:0)
	at android.app.ActivityThread.performDestroyActivity(Unknown Source:144)
	... 15 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl$Host.getWidgetUids(Unknown Source:25)
	at com.android.server.appwidget.AppWidgetServiceImpl.stopListening(Unknown Source:39)
	at com.android.internal.appwidget.IAppWidgetService$Stub.onTransact(Unknown Source:700)
	at android.os.Binder.execTransactInternal(Unknown Source:90)
	at android.os.Binder.execTransact(Unknown Source:16)

```

**Comment by gsantner** [comment]
![grafik](https://github.com/OpenLauncherTeam/openlauncher/assets/6735650/a80a5dfe-b26e-45f3-90c3-48be64e47e2f)
