### ISSUE TITLE
Crash on boot up

### ISSUE THREAD

**Issue by urbanomad64** [OpenLauncherTeam/openlauncher#77]
Build version: 0.3.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-01 07:48:04 
Device: UMI SUPER 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.benny.openlauncher.widget.CellContainer.onDraw(CellContainer.java:299)
	at android.view.View.draw(View.java:17320)
	at android.view.View.updateDisplayListIfDirty(View.java:16259)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:844)
	at android.view.View.draw(View.java:17332)
	at com.android.internal.policy.DecorView.draw(DecorView.java:830)
	at android.view.View.updateDisplayListIfDirty(View.java:16259)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3188)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2981)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2569)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
	at android.view.Choreographer.doCallbacks(Choreographer.java:709)
	at android.view.Choreographer.doFrame(Choreographer.java:644)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by dkanada** [comment]
I get the same error, I thought this was related to #71 but now it seems like a different issue altogether.

**Comment by BennyKok** [comment]
Are you guys still having this kind of issue with the latest version

**Comment by dkanada** [comment]
Yeah, I test all my changes on my personal phone so I am on the latest commit and this issue is still present.

**Comment by BennyKok** [comment]
ok this should be ok now in the latest commit

**Comment by dkanada** [comment]
Just updated and I am still getting a crash at [301](https://github.com/OpenLauncherTeam/openlauncher/blob/7523cc490f16dc6221d6b33b93462883eebcf5a8/app/src/main/java/com/benny/openlauncher/widget/CellContainer.java#L301) in the CellContainer class.

**Comment by BennyKok** [comment]
ha ha try again this time, I am using the wrong "&&" , should be "||"

**Comment by dkanada** [comment]
No issues now, thanks for the fix.
