### ISSUE TITLE
Crash when started: Unable to start activity

### ISSUE THREAD

**Issue by spagy** [OpenLauncherTeam/openlauncher#79]
this launcher looks pretty cool. unfortunately, i can't check it out because it crashes with the following as soon as i open it:
```
Build version: 0.3.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-01 19:18:54 
Device: Sony E2105 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.benny.openlauncher/com.benny.openlauncher.activity.Home}: android.view.InflateException: Binary XML file line #51: Error inflating class <unknown>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2436)
	at android.app.ActivityThread.access$800(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5398)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #51: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.benny.openlauncher.activity.Home.onCreate(Home.java:194)
	at android.app.Activity.performCreate(Activity.java:5264)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2349)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	... 27 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-nodpi-v4/ic_settings_launcher_36dp.xml from drawable resource ID #0x7f020084
	at android.content.res.Resources.loadDrawable(Resources.java:2166)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.widget.TextView.<init>(TextView.java:835)
	at android.widget.TextView.<init>(TextView.java:644)
	... 30 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:961)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:895)
	at android.content.res.Resources.loadDrawable(Resources.java:2162)
	... 33 more
```

**Comment by BennyKok** [comment]
Yeah I realize this error on many device with Android version lower than 5.0, but I am not sure if this still happen on the latest version.

**Comment by BennyKok** [comment]
What version of android are you using?

**Comment by spagy** [comment]
i'm on android 4.4.4.

i'll update open launcher, when the fdroid build is updated

**Comment by manikanta1219** [comment]
Hii friends i'll fix it.This error is only on Android version lower than 5.0.
In drawable-nodpi we have " ic_settings_launcher_36dp.xml "this file so please change drawable-nodpi to drawable.In current updated launcher issue alredy solved..
