### ISSUE TITLE
"All Apps" Action disappears when moved

### ISSUE THREAD

**Issue by aabaker** [OpenLauncherTeam/openlauncher#81]
Running today's HEAD, I can add the All Apps action to the Desktop but when I attempt to move it to the Dock or elsewhere on the Desktop it disappears. It isn't completely gone, attempting to move another item over it reports not enough space and the dock size increases so it is being written to the db.

Attempting to move one back from Dock to Desktop generated

`05-02 23:18:10.217 17510-17510/? E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                                                          java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference
                                                              at com.benny.openlauncher.widget.Desktop$DesktopAdapter$2.onItemRearrange(Desktop.java:488)
                                                              at com.benny.openlauncher.widget.CellContainer.onItemRearrange(CellContainer.java:140)
                                                              at com.benny.openlauncher.widget.CellContainer.peekItemAndSwap(CellContainer.java:131)
                                                              at com.benny.openlauncher.widget.Desktop.onDrag(Desktop.java:203)
                                                              at android.view.View.dispatchDragEvent(View.java:18438)
                                                              at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1387)
                                                              at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1336)
                                                              at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1336)
`

**Comment by dkanada** [comment]
I think this is related to a commit I pushed earlier today, I will fix this tomorrow.
