### ISSUE TITLE
Crash on boot up v. 0.3.2.1

### ISSUE THREAD

**Issue by urbanomad64** [OpenLauncherTeam/openlauncher#86]
Build version: 0.3.2.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-07 09:17:22 
Device: UMI SUPER 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.benny.openlauncher.widget.CellContainer.onDraw(CellContainer.java:299)
	at android.view.View.draw(View.java:17320)
	at android.view.View.updateDisplayListIfDirty(View.java:16259)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.View.draw(View.java:17070)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3890)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3676)
	at android.view.View.updateDisplayListIfDirty(View.java:16251)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3874)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3854)
	at android.view.View.updateDisplayListIfDirty(View.java:16213)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3188)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2981)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2569)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
	at android.view.Choreographer.doCallbacks(Choreographer.java:709)
	at android.view.Choreographer.doFrame(Choreographer.java:644)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by neolovich** [comment]
I'm not sure but maybe i have the same crash. Here the log:

Build version: 0.3.2.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-07 16:48:00 
Device: Fairphone FP2 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
	at com.benny.openlauncher.viewutil.ItemViewFactory.getGroupIconDrawable(ItemViewFactory.java:279)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:229)
	at com.benny.openlauncher.widget.Desktop.addItemToPoint(Desktop.java:306)
	at com.benny.openlauncher.widget.Desktop.onDrag(Desktop.java:211)
	at android.view.View.dispatchDragEvent(View.java:18446)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1388)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1374)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5181)
	at android.view.ViewRootImpl.access$600(ViewRootImpl.java:99)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3369)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by dkanada** [comment]
@urbanomad64: After you close the crash activity are you able to use the launcher? That issue is fixed in the 0.4.0 update which we released a few days ago.

@neolovich: I think your error happens when you drag an item directly from the app drawer into a group item and then try to move the group item, can you try that out and see if you get the same error? I will work on fixing it, but for now to work around the crash you can add the app to the desktop before moving it into a group.

**Comment by neolovich** [comment]
@dkanada: You are right. 

> error happens when you drag an item directly from the app drawer into a group item and then try to move the group item

Version 0.4.0 isn't available yet in F-Droid.

**Comment by urbanomad64** [comment]
@dkanada yes, that issue seems to be fixed but see my new issues ;-)

**Comment by dkanada** [comment]
@neolovich your issue should be fixed now since 0.4.0 has been added to F-Droid but if it isn't feel free to let me know.
