### ISSUE TITLE
Crash opening drawer after uninstalling app

### ISSUE THREAD

**Issue by zeehio** [OpenLauncherTeam/openlauncher#89]
I uninstalled an app dragging it from the drawer to the "Remove" tag on the top of the desktop screen.

I then touched the app drawer, the app uninstalled properly and I got the following crash with stack trace

```
Build version: 0.3.2.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-08 15:40:57 
Device: LGE Nexus 5X 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.benny.openlauncher.util.DatabaseHelper.getDesktop(DatabaseHelper.java:116)
	at com.benny.openlauncher.widget.Desktop.init(Desktop.java:79)
	at com.benny.openlauncher.activity.Home.initViews(Home.java:353)
	at com.benny.openlauncher.activity.Home.init(Home.java:248)
	at com.benny.openlauncher.activity.Home.access$200(Home.java:78)
	at com.benny.openlauncher.activity.Home$3.onPostExecute(Home.java:232)
	at com.benny.openlauncher.activity.Home$3.onPostExecute(Home.java:215)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
I upgraded yesterday to the latest f-droid version and I had to reset the app data because no icon or widget appeared on the desktop. Now I am getting a crash every time, I will try to restart the phone, otherwise I will have to reset the settings again.

**Comment by zeehio** [comment]
Can't reproduce with 0.5.1, maybe it's fixed
