### ISSUE TITLE
Crashes while relocating a folder

### ISSUE THREAD

**Issue by namjmnam** [OpenLauncherTeam/openlauncher#90]
Build version: 0.3.2.1 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-08 23:08:04 
Device: LGE Nexus 5 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
	at com.benny.openlauncher.viewutil.ItemViewFactory.getGroupIconDrawable(ItemViewFactory.java:279)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:229)
	at com.benny.openlauncher.widget.Desktop.addItemToPoint(Desktop.java:306)
	at com.benny.openlauncher.widget.Desktop.onDrag(Desktop.java:211)
	at android.view.View.dispatchDragEvent(View.java:19697)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1532)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1518)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1518)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1518)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1518)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1518)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1518)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:5282)
	at android.view.ViewRootImpl.-wrap6(ViewRootImpl.java)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3457)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

This happens too often. It also happens when relocating a widget.

**Comment by dkanada** [comment]
Can you also post an error message from the widget crash? I think they may be different because this looks like an issue with the group icons which wouldn't be related to moving a widget.

**Comment by dkanada** [comment]
Your issue should be fixed in the new update on F-Droid. I am not sure if the widgets are fixed so please post a crash log if you are still having problems.
