### ISSUE TITLE
Crash when opening app drawer

### ISSUE THREAD

**Issue by urbanomad64** [OpenLauncherTeam/openlauncher#94]
I have a crash when opening the app drawer and cannot remove the current icon, I added a new one which works but now have two on my home screen. 
Build version: 0.4.0 
Build date: 1980-01-01 00:00:00 
Current date: 2017-05-12 05:46:05 
Device: UMI SUPER 
 
Stack trace:  
android.content.ActivityNotFoundException: No Activity found to handle Intent {  }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
	at android.app.Activity.startActivityForResult(Activity.java:4226)
	at android.app.Activity.startActivityForResult(Activity.java:4185)
	at android.app.Activity.startActivity(Activity.java:4509)
	at android.app.Activity.startActivity(Activity.java:4477)
	at com.benny.openlauncher.widget.AppItemView$Builder$4$1.run(AppItemView.java:378)
	at com.benny.openlauncher.util.Tool$7$1.run(Tool.java:552)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by dkanada** [comment]
I just changed the code for the action items so that we could add new actions to the desktop in the future, this probably broke any old copies in the database, sorry about that. You can fix this by removing the data for this app and then rebuilding your desktop again. Right now the only way to do that is through a third party app or by uninstalling and reinstalling, but I will add a button in the settings soon to remove app data. We are making a lot of changes to the backend right now and the app is in alpha but it should be a lot more stable around 0.5.0 when we finish up the new backend stuff.

**Comment by ngm** [comment]
In case it helps anyone: I was also getting an error when opening the app drawer (don't have the logs unfortunately).  I added an App Drawer desktop action to the desktop, opened it, it worked fine, and then the main app drawer started working again (so can remove the newly created desktop action.)
