### ISSUE TITLE
Constant crash on launch or going home. Android O

### ISSUE THREAD

**Issue by EroticD** [OpenLauncherTeam/openlauncher#99]
Build version: 0.4.0 
Build date: 1979-11-30 01:00:00 
Current date: 2017-05-12 17:53:12 
Device: LGE Nexus 5X 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
	at com.benny.openlauncher.viewutil.ItemViewFactory.getGroupIconDrawable(ItemViewFactory.java:284)
	at com.benny.openlauncher.viewutil.ItemViewFactory.getItemView(ItemViewFactory.java:234)
	at com.benny.openlauncher.widget.Dock.addItemToPage(Dock.java:211)
	at com.benny.openlauncher.widget.Dock.initDockItem(Dock.java:60)
	at com.benny.openlauncher.activity.Home$4.onAppUpdated(Home.java:284)
	at com.benny.openlauncher.util.AppManager$AsyncGetApps.onPostExecute(AppManager.java:222)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6408)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:232)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

**Comment by EroticD** [comment]
Also crashes after clean install.

**Comment by BennyKok** [comment]
We'll fix it.

**Comment by dkanada** [comment]
There is a new update on F-Droid, can you try that one out and make sure the app data is cleared beforehand? I am pretty sure 0.5.0 fixed this issue.

**Comment by gsantner** [comment]
Reopen if needed
